"""
MetrCheck AI — Controlled Deterministic Multilingual Localization Layer

Provides deterministic, template-driven localizations for:
- Statutory Field Labels (LM-001..LM-009, FS-001..FS-005)
- Compliance Statuses (PASS, FAIL, WARNING, NEEDS_REVIEW, NOT_APPLICABLE)
- Rule Explanations and Legal Findings across all 10 languages
- Recommendation Titles and Corrective Actions
- PDF Report Headings and Metadata Labels

NO UNCONTROLLED LLM TRANSLATIONS. All text is derived from verified statutory templates.
"""

from typing import Dict, Any, Optional, List

LOCALIZED_STATUSES: Dict[str, Dict[str, str]] = {
    "en": {"PASS": "PASS", "FAIL": "FAIL", "WARNING": "WARNING", "NEEDS_REVIEW": "NEEDS REVIEW", "NOT_APPLICABLE": "NOT APPLICABLE", "COMPLIANT": "COMPLIANT", "NON_COMPLIANT": "NON-COMPLIANT"},
    "hi": {"PASS": "उत्तीर्ण (पास)", "FAIL": "विफल", "WARNING": "चेतावनी", "NEEDS_REVIEW": "समीक्षा आवश्यक", "NOT_APPLICABLE": "लागू नहीं", "COMPLIANT": "अनुपालक", "NON_COMPLIANT": "गैर-अनुपालक"},
    "bn": {"PASS": "উত্তীর্ণ", "FAIL": "ব্যর্থ", "WARNING": "সতর্কতা", "NEEDS_REVIEW": "পর্যালোচনা প্রয়োজন", "NOT_APPLICABLE": "প্রযোজ্য নয়", "COMPLIANT": "সম্মত", "NON_COMPLIANT": "অসম্মত"},
    "mr": {"PASS": "उत्तीर्ण", "FAIL": "अपात्र", "WARNING": "सूचना", "NEEDS_REVIEW": "तपासणी आवश्यक", "NOT_APPLICABLE": "लागू नाही", "COMPLIANT": "सुसंगत", "NON_COMPLIANT": "असंगत"},
    "gu": {"PASS": "પાસ", "FAIL": "નિષ્ફળ", "WARNING": "ચેતવણી", "NEEDS_REVIEW": "સમીક્ષા જરૂરી", "NOT_APPLICABLE": "લાગુ નથી", "COMPLIANT": "સુસંગત", "NON_COMPLIANT": "બિન-સુસંગત"},
    "pa": {"PASS": "ਪਾਸ", "FAIL": "ਅਸਫ਼ਲ", "WARNING": "ਚੇਤਾਵਨੀ", "NEEDS_REVIEW": "ਜਾਂਚ ਦੀ ਲੋੜ", "NOT_APPLICABLE": "ਲਾਗੂ ਨਹੀਂ", "COMPLIANT": "ਪਾਲਣਾ", "NON_COMPLIANT": "ਗੈਰ-ਪਾਲਣਾ"},
    "ta": {"PASS": "தேர்ச்சி", "FAIL": "தோல்வி", "WARNING": "எச்சரிக்கை", "NEEDS_REVIEW": "மறுஆய்வு தேவை", "NOT_APPLICABLE": "பொருந்தாது", "COMPLIANT": "இணக்கமானது", "NON_COMPLIANT": "இணக்கமற்றது"},
    "te": {"PASS": "ఉత్తీర్ణం", "FAIL": "విఫలం", "WARNING": "హెచ్చరిక", "NEEDS_REVIEW": "సమీక్ష అవసరం", "NOT_APPLICABLE": "వర్తించదు", "COMPLIANT": "అనుగుణంగా ఉంది", "NON_COMPLIANT": "నిబంధనలకు విరుద్ధం"},
    "kn": {"PASS": "ಪಾಸಾಗಿದೆ", "FAIL": "ವಿಫಲವಾಗಿದೆ", "WARNING": "ಎಚ್ಚರಿಕೆ", "NEEDS_REVIEW": "ಪರಿಶೀಲನೆ ಅಗತ್ಯ", "NOT_APPLICABLE": "ಅನ್ವಯಿಸುವುದಿಲ್ಲ", "COMPLIANT": "ಅನುಸರಣೆಯಾಗಿದೆ", "NON_COMPLIANT": "ಅನುಸರಿಸಿಲ್ಲ"},
    "ml": {"PASS": "വിജയിച്ചു", "FAIL": "പരാജയം", "WARNING": "മുന്നറിയിപ്പ്", "NEEDS_REVIEW": "പരിശോധന ആവശ്യമാണ്", "NOT_APPLICABLE": "ബാധകമല്ല", "COMPLIANT": "അനുസൃതമാണ്", "NON_COMPLIANT": "അനുസൃതമല്ല"}
}

LOCALIZED_FIELD_LABELS: Dict[str, Dict[str, str]] = {
    "en": {
        "LM-001": "Manufacturer / Packer / Importer",
        "LM-002": "Common / Generic Name",
        "LM-003": "Net Quantity",
        "LM-004": "Maximum Retail Price (MRP)",
        "LM-005": "Consumer Care Details",
        "LM-006": "Country of Origin",
        "LM-007": "Unit Sale Price",
        "LM-008": "Date of Manufacture / Packing",
        "LM-009": "Misleading Declarations / Non-Standard Statements",
        "FS-001": "FSSAI Licence Number / Logo",
        "FS-002": "Name of Food",
        "FS-003": "List of Ingredients",
        "FS-004": "Nutritional Information Panel",
        "FS-005": "Date Marking (Best Before / Expiry)"
    },
    "hi": {
        "LM-001": "निर्माता / पैककर्ता / आयातक का विवरण",
        "LM-002": "उत्पाद का सामान्य / जेनेरिक नाम",
        "LM-003": "शुद्ध मात्रा / वजन",
        "LM-004": "अधिकतम खुदरा मूल्य (MRP)",
        "LM-005": "उपभोक्ता देखभाल विवरण",
        "LM-006": "मूल देश (Country of Origin)",
        "LM-007": "इकाई विक्रय मूल्य (Unit Sale Price)",
        "LM-008": "निर्माण / पैकिंग की तारीख",
        "LM-009": "भ्रामक घोषणाएं / गैर-मानक कथन",
        "FS-001": "एफएसएसएआई लाइसेंस नंबर / लोगो",
        "FS-002": "खाद्य पदार्थ का नाम",
        "FS-003": "सामग्री की सूची",
        "FS-004": "पोषण संबंधी जानकारी तालिका",
        "FS-005": "तिथि अंकन (सर्वोत्तम उपयोग / समाप्ति)"
    },
    "mr": {
        "LM-001": "उत्पादक / पॅकर / आयातदार माहिती",
        "LM-002": "उत्पादनाचे सामान्य नाव",
        "LM-003": "निव्वळ प्रमाण / वजन",
        "LM-004": "कमाल किरकोळ किंमत (MRP)",
        "LM-005": "ग्राहक सेवा तपशील",
        "LM-006": "मूळ देश",
        "LM-007": "प्रति एकक विक्री किंमत",
        "LM-008": "उत्पादन / पॅकिंग दिनांक",
        "LM-009": "दिशाभूल करणाऱ्या घोषणा / अमानक विधाने",
        "FS-001": "एफएसएसएआय परवाना क्रमांक",
        "FS-002": "अन्नाचे नाव",
        "FS-003": "घटकांची यादी",
        "FS-004": "पोषण माहिती तक्ता",
        "FS-005": "दिनांक नोंदणी"
    },
    "bn": {
        "LM-001": "প্রস্তুতকারক / প্যাকার / আমদানিকারক",
        "LM-002": "পণ্যের সাধারণ নাম",
        "LM-003": "নিট পরিমাণ / ওজন",
        "LM-004": "সর্বোচ্চ খুচরা মূল্য (MRP)",
        "LM-005": "গ্রাহক পরিষেবা বিবরণ",
        "LM-006": "উৎপত্তির দেশ",
        "LM-007": "একক বিক্রয় মূল্য",
        "LM-008": "উৎপাদন / প্যাকিংয়ের তারিখ",
        "LM-009": "বিভ্রান্তিকর ঘোষণা / অ-মানক বিবৃতি",
        "FS-001": "এফএসএসএআই লাইসেন্স নম্বর",
        "FS-002": "খাদ্যের নাম",
        "FS-003": "উপাদানের তালিকা",
        "FS-004": "পুষ্টি তথ্য প্যানেল",
        "FS-005": "তারিখ চিহ্নিতকরণ"
    },
    "gu": {
        "LM-001": "ઉત્પાદક / પેકર / આયાતકાર વિગતો",
        "LM-002": "ઉત્પાદનનું સામાન્ય નામ",
        "LM-003": "ચોખ્ખો જથ્થો / વજન",
        "LM-004": "મહત્તમ છૂટક કિંમત (MRP)",
        "LM-005": "ગ્રાહક સેવા વિગતો",
        "LM-006": "મૂળ દેશ",
        "LM-007": "યુનિટ વેચાણ કિંમત",
        "LM-008": "ઉત્પાદન / પેકિંગ તારીખ",
        "LM-009": "ગેરમાર્ગે દોરતી ઘોષણાઓ / બિન-પ્રમાણભૂત વિધાનો",
        "FS-001": "એફએસએસએઆઈ લાઇસન્સ નંબર",
        "FS-002": "ખાદ્ય પદાર્થનું નામ",
        "FS-003": "સામગ્રીની સૂચિ",
        "FS-004": "પોષણ માહિતી પેનલ",
        "FS-005": "તારીખ માર્કિંગ"
    },
    "pa": {
        "LM-001": "ਨਿਰਮਾਤਾ / ਪੈਕਰ / ਆਯਾਤਕ ਵੇਰਵਾ",
        "LM-002": "ਉਤਪਾਦ ਦਾ ਆਮ ਨਾਮ",
        "LM-003": "ਸ਼ੁੱਧ ਮਾਤਰਾ / ਭਾਰ",
        "LM-004": "ਵੱਧ ਤੋਂ ਵੱਧ ਪ੍ਰਚੂਨ ਮੁੱਲ (MRP)",
        "LM-005": "ਗਾਹਕ ਸੇਵਾ ਵੇਰਵਾ",
        "LM-006": "ਮੂਲ ਦੇਸ਼",
        "LM-007": "ਪ੍ਰਤੀ ਇਕਾਈ ਵਿਕਰੀ ਮੁੱਲ",
        "LM-008": "ਨਿਰਮਾਣ / ਪੈਕਿੰਗ ਮਿਤੀ",
        "LM-009": "ਗੁੰਮਰਾਹਕੁੰਨ ਘੋਸ਼ਣਾਵਾਂ / ਗੈਰ-ਮਿਆਰੀ ਬਿਆਨ",
        "FS-001": "ਐਫਐਸਐਸਏਆਈ ਲਾਇਸੈਂਸ ਨੰਬਰ",
        "FS-002": "ਭੋਜਨ ਦਾ ਨਾਮ",
        "FS-003": "ਸਮੱਗਰੀ ਦੀ ਸੂਚੀ",
        "FS-004": "ਪੋਸ਼ਣ ਜਾਣਕਾਰੀ ਪੈਨਲ",
        "FS-005": "ਮਿਤੀ ਨਿਸ਼ਾਨਦੇਹੀ"
    },
    "ta": {
        "LM-001": "உற்பத்தியாளர் / பேக்கர் / இறக்குமதியாளர் விவரம்",
        "LM-002": "தயாரிப்பின் பொதுவான பெயர்",
        "LM-003": "நிகர அளவு / எடை",
        "LM-004": "அதிகபட்ச சில்லறை விலை (MRP)",
        "LM-005": "வாடிக்கையாளர் சேவை விவரங்கள்",
        "LM-006": "பிறப்பிட நாடு",
        "LM-007": "அலகு விற்பனை விலை",
        "LM-008": "உற்பத்தி / பேக்கிங் தேதி",
        "LM-009": "தவறான அறிவிப்புகள் / தரமற்ற அறிக்கைகள்",
        "FS-001": "எஃப்எஸ்எஸ்ஏஐ உரிம எண்",
        "FS-002": "உணவின் பெயர்",
        "FS-003": "பொருட்களின் பட்டியல்",
        "FS-004": "ஊட்டச்சத்து தகவல் பலகை",
        "FS-005": "தேதி குறிப்பு"
    },
    "te": {
        "LM-001": "తయారీదారు / ప్యాకర్ / దిగుమతిదారు వివరాలు",
        "LM-002": "ఉత్పత్తి సాధారణ పేరు",
        "LM-003": "నికర పరిమాణం / బరువు",
        "LM-004": "గరిష్ట చిల్లర ధర (MRP)",
        "LM-005": "కస్టమర్ కేర్ వివరాలు",
        "LM-006": "మూల దేశం",
        "LM-007": "యూనిట్ అమ్మకపు ధర",
        "LM-008": "తయారీ / ప్యాకింగ్ తేదీ",
        "LM-009": "తప్పుదారి పట్టించే ప్రకటనలు / ప్రామాణికం కాని ప్రకటనలు",
        "FS-001": "ఎఫ్ఎస్ఎస్ఏఐ లైసెన్స్ సంఖ్య",
        "FS-002": "ఆహారం పేరు",
        "FS-003": "పదార్థాల జాబితా",
        "FS-004": "పోషకాహార సమాచార ప్యానెల్",
        "FS-005": "తేదీ మార్కింగ్"
    },
    "kn": {
        "LM-001": "ತಯಾರಕರು / ಪ್ಯಾಕರ್ ವಿವರಗಳು",
        "LM-002": "ಉತ್ಪನ್ನದ ಸಾಮಾನ್ಯ ಹೆಸರು",
        "LM-003": "ನಿವ್ವಳ ಪ್ರಮಾಣ / ತೂಕ",
        "LM-004": "ಗರಿಷ್ಠ ಚಿಲ್ಲರೆ ಬೆಲೆ (MRP)",
        "LM-005": "ಗ್ರಾಹಕ ಸೇವಾ ವಿವರಗಳು",
        "LM-006": "ಮೂಲ ದೇಶ",
        "LM-007": "ಪ್ರತಿ ಘಟಕದ ಮಾರಾಟ ಬೆಲೆ",
        "LM-008": "ತಯಾರಿಕಾ / ಪ್ಯಾಕಿಂಗ್ ದಿನಾಂಕ",
        "LM-009": "ದಾರಿತಪ್ಪಿಸುವ ಘೋಷಣೆಗಳು / ಅಪ್ರಮಾಣಿತ ಹೇಳಿಕೆಗಳು",
        "FS-001": "ಎಫ್‌ಎಸ್‌ಎಸ್‌ಎಐ ಪರವಾನಗಿ ಸಂಖ್ಯೆ",
        "FS-002": "ಆಹಾರದ ಹೆಸರು",
        "FS-003": "ಪದಾರ್ಥಗಳ ಪಟ್ಟಿ",
        "FS-004": "ಪೌಷ್ಟಿಕಾಂಶ ಮಾಹಿತಿ ಫಲಕ",
        "FS-005": "ದಿನಾಂಕ ನಮೂದು"
    },
    "ml": {
        "LM-001": "ഉത്പാദകർ / പാക്കർ വിവരങ്ങൾ",
        "LM-002": "ഉൽപ്പന്നത്തിന്റെ പേര്",
        "LM-003": "അറ്റ അളവ് / തൂക്കം",
        "LM-004": "പരമാവധി ചില്ലറ വിൽപ്പന വില (MRP)",
        "LM-005": "ഉപഭോക്തൃ സേവന വിവരങ്ങൾ",
        "LM-006": "ഉത്ഭവ രാജ്യം",
        "LM-007": "യൂണിറ്റ് വിൽപ്പന വില",
        "LM-008": "ഉത്പാദന / പാക്കിംഗ് തീയതി",
        "LM-009": "തെറ്റിദ്ധരിപ്പിക്കുന്ന പ്രഖ്യാപനങ്ങൾ / നിലവാരമില്ലാത്ത പ്രസ്താവനകൾ",
        "FS-001": "എഫ്എസ്എസ്എഐ ലൈസൻസ് നമ്പർ",
        "FS-002": "ഭക്ഷണത്തിന്റെ പേര്",
        "FS-003": "ചേരുവകളുടെ പട്ടിക",
        "FS-004": "പോഷകാഹാര വിവര പാനൽ",
        "FS-005": "തീയതി രേഖപ്പെടുത്തൽ"
    }
}

LOCALIZED_EXPLANATION_TEMPLATES: Dict[str, Dict[str, Dict[str, str]]] = {
    "en": {
        "PASS": {
            "LM-001": "Manufacturer/Packer name and address verified on packaging.",
            "LM-002": "Common/Generic name of commodity is clearly declared.",
            "LM-003": "Net quantity is declared in standard metric units.",
            "LM-004": "Maximum Retail Price (MRP) is clearly declared inclusive of all taxes.",
            "LM-005": "Consumer helpline/contact details are properly declared.",
            "LM-006": "Country of origin is declared as required for commodities.",
            "LM-007": "Unit sale price is declared in accordance with statutory guidelines.",
            "LM-008": "Date of manufacture/pre-packing is properly declared.",
            "LM-009": "Best before / relative shelf life is clearly indicated.",
            "FS-001": "Valid 14-digit FSSAI licence number is present on the package.",
            "FS-002": "Food name is clearly declared.",
            "FS-003": "Complete list of ingredients is declared in descending order.",
            "FS-004": "Nutritional information panel is properly displayed.",
            "FS-005": "Date marking (expiry/best before) is present."
        },
        "FAIL": {
            "LM-001": "Manufacturer or Packer declaration is missing or incomplete.",
            "LM-002": "Common or Generic name of the commodity is missing.",
            "LM-003": "Net quantity declaration is missing or in non-standard units.",
            "LM-004": "Maximum Retail Price (MRP) declaration could not be verified.",
            "LM-005": "Consumer care name, address, phone or email is missing.",
            "LM-006": "Country of origin is missing on the package.",
            "LM-007": "Unit sale price declaration is missing.",
            "LM-008": "Date of manufacture or packing is missing.",
            "LM-009": "Best before or expiry duration is missing.",
            "FS-001": "FSSAI licence number or logo is missing on food package.",
            "FS-002": "Standard food name is missing.",
            "FS-003": "Ingredients declaration is missing on food package.",
            "FS-004": "Nutritional information panel is missing.",
            "FS-005": "Mandatory date marking is missing."
        }
    },
    "hi": {
        "PASS": {
            "LM-001": "निर्माता/पैककर्ता का नाम एवं पता पैकेजिंग पर सत्यापित है।",
            "LM-002": "उत्पाद का सामान्य/जेनेरिक नाम स्पष्ट रूप से घोषित है।",
            "LM-003": "शुद्ध मात्रा मानक मीट्रिक इकाइयों में घोषित है।",
            "LM-004": "अधिकतम खुदरा मूल्य (MRP) सभी करों सहित स्पष्ट रूप से घोषित है।",
            "LM-005": "उपभोक्ता हेल्पलाइन/संपर्क विवरण नियमानुसार घोषित है।",
            "LM-006": "मूल देश (Country of Origin) नियमानुसार घोषित है।",
            "LM-007": "इकाई विक्रय मूल्य वैधानिक दिशानिर्देशों के अनुसार घोषित है।",
            "LM-008": "निर्माण/पैकिंग की तारीख उचित रूप से घोषित है।",
            "LM-009": "सर्वोत्तम उपयोग अवधि स्पष्ट रूप से दर्शायी गई है।",
            "FS-001": "मान्य 14-अंकीय एफएसएसएआई लाइसेंस नंबर पैकेज पर उपस्थित है।",
            "FS-002": "खाद्य पदार्थ का नाम स्पष्ट रूप से घोषित है।",
            "FS-003": "सामग्रियों की पूर्ण सूची घोषित है।",
            "FS-004": "पोषण संबंधी जानकारी तालिका पैकेज पर उपलब्ध है।",
            "FS-005": "तिथि अंकन (समाप्ति/सर्वोत्तम उपयोग) उपस्थित है।"
        },
        "FAIL": {
            "LM-001": "निर्माता या पैककर्ता का विवरण पैकेज पर गायब या अधूरा है।",
            "LM-002": "उत्पाद का सामान्य या जेनेरिक नाम अनुपस्थित है।",
            "LM-003": "शुद्ध मात्रा की घोषणा अनुपस्थित है या अमानक इकाई में है।",
            "LM-004": "अधिकतम खुदरा मूल्य (MRP) की घोषणा सत्यापित नहीं की जा सकी।",
            "LM-005": "उपभोक्ता सेवा फोन/ईमेल संपर्क विवरण गायब है।",
            "LM-006": "मूल देश की घोषणा पैकेज पर नहीं मिली।",
            "LM-007": "इकाई विक्रय मूल्य की घोषणा गायब है।",
            "LM-008": "निर्माण या पैकिंग की तारीख अनुपस्थित है।",
            "LM-009": "समाप्ति या सर्वोत्तम उपयोग अवधि गायब है।",
            "FS-001": "एफएसएसएआई लाइसेंस नंबर या लोगो खाद्य पैकेज पर नहीं मिला।",
            "FS-002": "मानक खाद्य नाम अनुपस्थित है।",
            "FS-003": "सामग्री सूची खाद्य पैकेज पर नहीं मिली।",
            "FS-004": "पोषण संबंधी जानकारी तालिका गायब है।",
            "FS-005": "अनिवार्य तिथि अंकन गायब है।"
        }
    }
}

REPORT_UI_LABELS: Dict[str, Dict[str, str]] = {
    "en": {
        "report_title": "AI-Assisted Product Compliance Screening Report",
        "subtitle": "Department of Consumer Affairs, Government of India",
        "overall_status": "STATUTORY COMPLIANCE SCREENING RESULT",
        "compliance_score": "Compliance Score",
        "screening_score": "SCREENING SCORE",
        "product_name": "Product Name",
        "brand": "Brand",
        "analysis_id": "Analysis ID",
        "analysis_mode": "Analysis Mode",
        "manual_mode": "MANUAL PRODUCT CHECK",
        "image_mode": "AI IMAGE & OCR SCREENING",
        "info_source": "Information Source",
        "manual_source": "USER-PROVIDED PACKAGE DECLARATIONS",
        "image_source": "PACKAGE ARTWORK OCR & COMPUTER VISION",
        "inspection_timestamp": "Inspection Timestamp",
        "generated_at": "Report Generated At",
        "product_risk_tier": "Product Risk Tier",
        "images_analyzed": "Images Analyzed",
        "detected_languages": "Packaging Languages",
        "statutory_declarations": "Statutory Declarations (Rule 6)",
        "executive_summary": "EXECUTIVE SUMMARY & PRODUCT OVERVIEW",
        "legal_disclaimer": "Legal Disclaimer & Statutory Scope",
        "items_requiring_attention": "ITEMS REQUIRING ATTENTION & WHAT THIS MEANS",
        "what_this_means": "What this means",
        "detected": "Detected",
        "all_pass_msg": "All statutory packaging declarations analyzed meet automated screening criteria. No items require immediate attention.",
        "automated_score_note": "This score is a weighted automated screening score across applicable checks. It is not an official legal compliance percentage or enforcement determination.",
        "manual_score_note": "This screening is based on declarations manually provided by the consumer. Some declaration information in this report was provided manually and was not independently verified against package artwork.",
        "package_information_summary": "PACKAGE INFORMATION SUMMARY",
        "marketed_by": "Marketed By",
        "best_before_shelf_life": "Best Before / Shelf Life",
        "batch_lot_number": "Batch / Lot Number",
        "readability_title": "PHYSICAL READABILITY & QUANTITY DECLARATION ASSESSMENT",
        "readability_score_tier": "Visual Readability Score & Tier",
        "net_qty_font_height": "Estimated Net Qty Character Height",
        "min_required_font_height": "Statutory Minimum Required Height",
        "rule_12_verdict": "Rule 12 Screening Verdict",
        "measurement_method": "Measurement Method & Optical Scale",
        "assessment_summary": "Assessment Summary",
        "rule12_notice": "Estimated measurements are derived from digital image analysis and optical scale estimation. They should not be treated as a physically calibrated measurement certificate.",
        "no_img_msg": "Package artwork was not submitted for this manual screening. Physical readability and optical measurements were not assessed.",
        "external_verification_title": "EXTERNAL REGISTRY VERIFICATION & CROSS-CHECKING",
        "overall_cross_check_status": "Overall Cross-Check Status",
        "verification_confidence_tier": "Verification Confidence Tier",
        "authoritative_verdict": "Authoritative Verdict",
        "verification_sources": "Verification Sources",
        "cross_check_target": "Cross-Check Target",
        "extracted_value": "Extracted Value",
        "registry_record": "Registry Record",
        "human_review_title": "HUMAN OFFICER AUDIT REVIEW",
        "review_workflow_status": "Review Workflow Status",
        "assigned_officer": "Assigned Legal Metrology Officer",
        "verified_by_officer": "Verified By Officer",
        "verification_timestamp": "Verification Timestamp",
        "final_human_verdict": "Final Human Compliance Verdict",
        "human_verified_score": "Human Verified Score",
        "ai_vs_human_delta": "AI vs Human Score Delta",
        "officer_notes": "Officer Notes & Comments",
        "detailed_compliance_checklist": "DETAILED STATUTORY COMPLIANCE CHECKLIST",
        "legal_metrology_title": "LEGAL METROLOGY (PACKAGED COMMODITIES) RULES 2011",
        "fssai_title": "FSSAI (FOOD SAFETY & STANDARDS LABELLING REGULATIONS)",
        "field_header": "Rule ID",
        "requirement_header": "Statutory Requirement",
        "status_header": "Status",
        "detected_value_header": "Detected Declaration",
        "finding_header": "Legal Finding",
        "evidence": "Evidence",
        "location_header": "Location",
        "confidence_header": "Confidence",
        "recommended_check": "Recommended Check",
        "recommended_actions_title": "RECOMMENDED NEXT STEPS & ACTIONS",
        "priority_header": "Priority",
        "rule_title_header": "Rule & Title",
        "issue_header": "Issue Identified",
        "recommended_action_header": "Recommended Action",
        "statutory_basis_header": "Statutory Basis",
        "no_rec_msg": "No corrective actions required based on automated screening.",
        "visual_evidence_title": "VISUAL EVIDENCE APPENDIX",
        "security_integrity_title": "SECURITY, INTEGRITY & AUDIT PROVENANCE",
        "integrity_hash_label": "Cryptographic Integrity Hash (SHA-256)",
        "software_version_label": "System Software Version",
        "ruleset_version_label": "Statutory Ruleset Version",
        "ocr_engine_label": "OCR & Vision Engine",
        "audit_status_label": "Audit Verification Status",
        "verification_notice_label": "Verification Notice",
        "evidence_summary": "Evidence Chain Summary",
        "page": "Page",
        "disclaimer": "MetrCheck AI provides AI-assisted packaging compliance screening based on the images submitted for analysis. Results may require physical verification and should not be treated as an official enforcement determination.",
    },
    "hi": {
        "report_title": "एआई-सहायित उत्पाद अनुपालन स्क्रीनिंग रिपोर्ट",
        "subtitle": "उपभोक्ता मामले विभाग, भारत सरकार",
        "overall_status": "वैधानिक अनुपालन स्क्रीनिंग परिणाम",
        "compliance_score": "अनुपालन स्कोर",
        "screening_score": "स्क्रीनिंग स्कोर",
        "product_name": "उत्पाद का नाम",
        "brand": "ब्रांड",
        "analysis_id": "विश्लेषण आईडी",
        "analysis_mode": "विश्लेषण मोड",
        "manual_mode": "मैन्युअल उत्पाद जांच",
        "image_mode": "एआई छवि एवं OCR स्क्रीनिंग",
        "info_source": "सूचना स्रोत",
        "manual_source": "उपभोक्ता द्वारा प्रदान की गई घोषणाएं",
        "image_source": "पैकेज आर्टवर्क OCR एवं कंप्यूटर विज़न",
        "inspection_timestamp": "निरीक्षण समय",
        "generated_at": "रिपोर्ट निर्माण समय",
        "product_risk_tier": "उत्पाद जोखिम स्तर",
        "images_analyzed": "विश्लेषित छवियां",
        "detected_languages": "पहचानी गई पैकेजिंग भाषाएं",
        "statutory_declarations": "वैधानिक घोषणाएं (नियम 6)",
        "executive_summary": "कार्यकारी सारांश एवं उत्पाद अवलोकन",
        "legal_disclaimer": "कानूनी अस्वीकरण एवं वैधानिक दायरा",
        "items_requiring_attention": "ध्यान देने योग्य बिंदु एवं उनका अर्थ",
        "what_this_means": "इसका क्या अर्थ है",
        "detected": "पहचाना गया",
        "all_pass_msg": "विश्लेषित सभी वैधानिक पैकेजिंग घोषणाएं स्वचालित स्क्रीनिंग मानदंडों को पूरा करती हैं। किसी भी बिंदु पर तत्काल ध्यान देने की आवश्यकता नहीं है।",
        "automated_score_note": "यह स्कोर लागू जांचों में भारित स्वचालित स्क्रीनिंग स्कोर है। यह आधिकारिक कानूनी अनुपालन प्रतिशत या प्रवर्तन निर्धारण नहीं है।",
        "manual_score_note": "यह स्क्रीनिंग उपभोक्ता द्वारा मैन्युअल रूप से प्रदान की गई घोषणाओं पर आधारित है। इस रिपोर्ट में कुछ जानकारी स्वतंत्र रूप से सत्यापित नहीं की गई थी।",
        "package_information_summary": "पैकेज सूचना सारांश",
        "marketed_by": "विपणनकर्ता विवरण",
        "best_before_shelf_life": "उपयोग की अंतिम तिथि / शेल्फ लाइफ",
        "batch_lot_number": "बैच / लॉट संख्या",
        "readability_title": "भौतिक पठनीयता एवं मात्रा घोषणा मूल्यांकन",
        "readability_score_tier": "दृश्य पठनीयता स्कोर एवं स्तर",
        "net_qty_font_height": "अनुमानित शुद्ध मात्रा फ़ॉन्ट ऊंचाई",
        "min_required_font_height": "न्यूनतम आवश्यक वैधानिक ऊंचाई",
        "rule_12_verdict": "नियम 12 स्क्रीनिंग निर्णय",
        "measurement_method": "मापन विधि एवं ऑप्टिकल स्केल",
        "assessment_summary": "मूल्यांकन सारांश",
        "rule12_notice": "अनुमानित माप डिजिटल छवि विश्लेषण से प्राप्त किए गए हैं। इन्हें भौतिक रूप से कैलिब्रेटेड प्रमाणपत्र नहीं माना जाना चाहिए।",
        "no_img_msg": "इस मैन्युअल स्क्रीनिंग के लिए पैकेज आर्टवर्क जमा नहीं किया गया था। भौतिक पठनीयता का मूल्यांकन नहीं किया गया।",
        "external_verification_title": "बाह्य रजिस्ट्री सत्यापन एवं क्रॉस-जांच",
        "overall_cross_check_status": "समग्र क्रॉस-जांच स्थिति",
        "verification_confidence_tier": "सत्यापन विश्वसनीयता स्तर",
        "authoritative_verdict": "प्रामाणिक निर्णय",
        "verification_sources": "सत्यापन स्रोत",
        "cross_check_target": "सत्यापन लक्ष्य",
        "extracted_value": "निष्कर्षित मान",
        "registry_record": "रजिस्ट्री रिकॉर्ड",
        "human_review_title": "मानव अधिकारी ऑडिट समीक्षा",
        "review_workflow_status": "समीक्षा वर्कफ़्लो स्थिति",
        "assigned_officer": "नियुक्त विधिक मापविज्ञान अधिकारी",
        "verified_by_officer": "अधिकारी द्वारा सत्यापित",
        "verification_timestamp": "सत्यापन समय टिकट",
        "final_human_verdict": "अंतिम मानव अनुपालन निर्णय",
        "human_verified_score": "मानव सत्यापित स्कोर",
        "ai_vs_human_delta": "AI बनाम मानव स्कोर अंतर",
        "officer_notes": "अधिकारी टिप्पणियां",
        "detailed_compliance_checklist": "विस्तृत वैधानिक अनुपालन चेकलिस्ट",
        "legal_metrology_title": "विधिक मापविज्ञान (पैकेज्ड वस्तुएं) नियम 2011",
        "fssai_title": "FSSAI (खाद्य सुरक्षा एवं मानक लेबलिंग विनियम)",
        "field_header": "नियम आईडी",
        "requirement_header": "वैधानिक आवश्यकता",
        "status_header": "स्थिति",
        "detected_value_header": "पहचानी गई घोषणा",
        "finding_header": "कानूनी निष्कर्ष",
        "evidence": "साक्ष्य",
        "location_header": "स्थान",
        "confidence_header": "विश्वास",
        "recommended_check": "अनुशंसित जांच",
        "recommended_actions_title": "अनुशंसित अगले कदम एवं कार्रवाइयां",
        "priority_header": "प्राथमिकता",
        "rule_title_header": "नियम एवं शीर्षक",
        "issue_header": "पहचानी गई समस्या",
        "recommended_action_header": "अनुशंसित कार्रवाई",
        "statutory_basis_header": "वैधानिक आधार",
        "no_rec_msg": "स्वचालित स्क्रीनिंग के आधार पर किसी सुधारात्मक कार्रवाई की आवश्यकता नहीं है।",
        "visual_evidence_title": "दृश्य साक्ष्य परिशिष्ट",
        "security_integrity_title": "सुरक्षा, सत्यनिष्ठा एवं ऑडिट उद्भव",
        "integrity_hash_label": "क्रिप्टोग्राफ़िक सत्यनिष्ठा हैश (SHA-256)",
        "software_version_label": "सिस्टम सॉफ्टवेयर संस्करण",
        "ruleset_version_label": "वैधानिक नियमसेट संस्करण",
        "ocr_engine_label": "OCR एवं विज़न इंजन",
        "audit_status_label": "ऑडिट सत्यापन स्थिति",
        "verification_notice_label": "सत्यापन सूचना",
        "evidence_summary": "साक्ष्य श्रृंखला सारांश",
        "page": "पृष्ठ",
        "disclaimer": "मेट्रचेक एआई विश्लेषण हेतु प्रस्तुत छवियों के आधार पर एआई-सहायित पैकेजिंग अनुपालन स्क्रीनिंग प्रदान करता है। परिणाम आधिकारिक प्रवर्तन निर्धारण नहीं हैं।",
    },
    "mr": {
        "report_title": "एआय-सहाय्यित उत्पादन अनुपालन तपासणी अहवाल",
        "subtitle": "ग्राहक व्यवहार विभाग, भारत सरकार",
        "overall_status": "कायदेशीर अनुपालन तपासणी निकाल",
        "compliance_score": "अनुपालन गुण",
        "screening_score": "स्क्रीनिंग गुण",
        "product_name": "उत्पादनाचे नाव",
        "brand": "ब्रँड",
        "analysis_id": "विश्लेषण आयडी",
        "analysis_mode": "विश्लेषण मोड",
        "manual_mode": "मॅन्युअल उत्पादन तपासणी",
        "image_mode": "एआय प्रतिमा आणि OCR तपासणी",
        "info_source": "माहिती स्रोत",
        "manual_source": "ग्राहकाने प्रदान केलेल्या घोषणा",
        "image_source": "पॅकेज आर्टवर्क OCR आणि संगणक दृष्टी",
        "inspection_timestamp": "तपासणी वेळ",
        "generated_at": "अहवाल निर्मिती वेळ",
        "product_risk_tier": "उत्पादन जोखीम स्तर",
        "images_analyzed": "विश्लेषित प्रतिमा",
        "detected_languages": "आढळलेल्या पॅकेजिंग भाषा",
        "statutory_declarations": "वैधानिक घोषणा (नियम ६)",
        "executive_summary": "कार्यकारी सारांश आणि उत्पादन विहंगावलोकन",
        "legal_disclaimer": "कायदेशीर अस्वीकरण आणि वैधानिक व्याप्ती",
        "items_requiring_attention": "लक्षात घेण्यासारखे मुद्दे आणि त्यांचा अर्थ",
        "what_this_means": "याचा अर्थ काय आहे",
        "detected": "शोधले गेले",
        "all_pass_msg": "विश्लेषित केलेल्या सर्व वैधानिक पॅकेजिंग घोषणा स्वयंचलित तपासणी निकष पूर्ण करतात. कोणत्याही मुद्द्यावर तात्काळ लक्ष देण्याची गरज नाही.",
        "automated_score_note": "हा गुण स्वयंचलित तपासणीचा भारित गुण आहे. ही अधिकृत कायदेशीर अनुपालन टक्केवारी नाही.",
        "manual_score_note": "ही तपासणी ग्राहकाने मॅन्युअली दिलेल्या घोषणांवर आधारित आहे. या अहवालातील काही माहिती स्वतंत्रपणे पडताळलेली नाही.",
        "package_information_summary": "पॅकेज माहिती सारांश",
        "marketed_by": "विपणनकर्त्याचा तपशील",
        "best_before_shelf_life": "वापरण्याची अंतिम तारीख / शेल्फ लाइफ",
        "batch_lot_number": "बॅच / लॉट क्रमांक",
        "readability_title": "भौतिक वाचनीयता आणि प्रमाण घोषणा मूल्यांकन",
        "readability_score_tier": "दृश्य वाचनीयता गुण आणि स्तर",
        "net_qty_font_height": "अंदाजे निव्वळ प्रमाण फॉन्ट उंची",
        "min_required_font_height": "किमान आवश्यक कायदेशीर उंची",
        "rule_12_verdict": "नियम १२ तपासणी निकाल",
        "measurement_method": "मोजमाप पद्धत आणि ऑप्टिकल स्केल",
        "assessment_summary": "मूल्यांकन सारांश",
        "rule12_notice": "अंदाजे मोजमापे डिजिटल प्रतिमा विश्लेषणातून घेतली आहेत. त्यांना भौतिकदृष्ट्या कॅलिब्रेट केलेले प्रमाणपत्र मानू नये.",
        "no_img_msg": "या मॅन्युअल तपासणीसाठी पॅकेज आर्टवर्क सबमिट केले नव्हते. भौतिक वाचनीयतेचे मूल्यांकन केले गेले नाही.",
        "external_verification_title": "बाह्य नोंदणी पडताळणी आणि क्रॉस-तपासणी",
        "overall_cross_check_status": "एकूण क्रॉस-तपासणी स्थिती",
        "verification_confidence_tier": "पडताळणी विश्वासार्हता स्तर",
        "authoritative_verdict": "अधिकृत निकाल",
        "verification_sources": "पडताळणी स्रोत",
        "cross_check_target": "पडताळणी लक्ष्य",
        "extracted_value": "काढलेले मूल्य",
        "registry_record": "नोंदणी माहिती",
        "human_review_title": "मानवी अधिकारी ऑडिट पुनरावलोकन",
        "review_workflow_status": "पुनरावलोकन कार्यप्रवाह स्थिती",
        "assigned_officer": "नियुक्त कायदेशीर मेट्रोलॉजी अधिकारी",
        "verified_by_officer": "अधिकाऱ्याद्वारे पडताळलेले",
        "verification_timestamp": "पडताळणी वेळ नोंद",
        "final_human_verdict": "अंतिम मानवी अनुपालन निकाल",
        "human_verified_score": "मानव पडताळणी गुण",
        "ai_vs_human_delta": "AI विरुद्ध मानव गुण फरक",
        "officer_notes": "अधिकारी टिप्पण्या",
        "detailed_compliance_checklist": "तपशीलवार वैधानिक अनुपालन चेकलिस्ट",
        "legal_metrology_title": "विधिक मापविज्ञान (पॅक केलेल्या वस्तू) नियम २०११",
        "fssai_title": "FSSAI (अन्न सुरक्षा आणि मानके लेबलिंग नियमन)",
        "field_header": "नियम आयडी",
        "requirement_header": "वैधानिक आवश्यकता",
        "status_header": "स्थिती",
        "detected_value_header": "आढळलेली घोषणा",
        "finding_header": "कायदेशीर निष्कर्ष",
        "evidence": "पुरावा",
        "location_header": "स्थान",
        "confidence_header": "विश्वास",
        "recommended_check": "शिफारस केलेली तपासणी",
        "recommended_actions_title": "पुढील शिफारस केलेल्या कृती",
        "priority_header": "प्राधान्य",
        "rule_title_header": "नियम आणि शीर्षक",
        "issue_header": "आढळलेली समस्या",
        "recommended_action_header": "शिफारस केलेली कृती",
        "statutory_basis_header": "कायदेशीर आधार",
        "no_rec_msg": "स्वयंचलित तपासणीच्या आधारे कोणत्याही सुधारात्मक कृतीची आवश्यकता नाही.",
        "visual_evidence_title": "दृश्य पुरावा परिशिष्ट",
        "security_integrity_title": "सुरक्षा, अखंडता आणि ऑडिट उद्भव",
        "integrity_hash_label": "क्रिप्टोग्राफिक इंटिग्रिटी हॅश (SHA-256)",
        "software_version_label": "सिस्टम सॉफ्टवेअर आवृत्ती",
        "ruleset_version_label": "वैधानिक नियमसेट आवृत्ती",
        "ocr_engine_label": "OCR आणि व्हिजन इंजिन",
        "audit_status_label": "ऑडिट पडताळणी स्थिती",
        "verification_notice_label": "पडताळणी सूचना",
        "evidence_summary": "पुरावा साखळी सारांश",
        "page": "पृष्ठ",
        "disclaimer": "मेट्रचेक एआय विश्लेषणासाठी सादर केलेल्या प्रतिमांच्या आधारे तपासणी प्रदान करते. निकाल अधिकृत अंमलबजावणी निर्धारण मानले जाऊ नयेत.",
    },
    "bn": {
        "report_title": "এআই-সহায়তাপ্রাপ্ত পণ্য সম্মতি স্ক্রিনিং প্রতিবেদন",
        "subtitle": "ভোক্তা বিষয়ক বিভাগ, ভারত সরকার",
        "overall_status": "বিধিবদ্ধ সম্মতি স্ক্রিনিং ফলাফল",
        "compliance_score": "সম্মতি স্কোর",
        "screening_score": "স্ক্রিনিং স্কোর",
        "product_name": "পণ্যের নাম",
        "brand": "ব্র্যান্ড",
        "analysis_id": "বিশ্লেষণ আইডি",
        "analysis_mode": "বিশ্লেষণ মোড",
        "manual_mode": "ম্যানুয়াল পণ্য পরীক্ষা",
        "image_mode": "এআই ছবি ও OCR স্ক্রিনিং",
        "info_source": "তথ্য উৎস",
        "manual_source": "ভোক্তা দ্বারা প্রদত্ত ঘোষণা",
        "image_source": "প্যাকেজ আর্টওয়ার্ক OCR এবং কম্পিউটার ভিশন",
        "inspection_timestamp": "পরিদর্শনের সময়",
        "generated_at": "প্রতিবেদন তৈরির সময়",
        "product_risk_tier": "পণ্য ঝুঁকি স্তর",
        "images_analyzed": "বিশ্লেষিত ছবি",
        "detected_languages": "সনাক্তকৃত প্যাকেজিং ভাষা",
        "statutory_declarations": "বিধিবদ্ধ ঘোষণা (নিয়ম ৬)",
        "executive_summary": "কার্যনির্বাহী সারাংশ ও পণ্য পরিচিতি",
        "legal_disclaimer": "আইনি দাবিত্যাগ ও বিধিবদ্ধ পরিধি",
        "items_requiring_attention": "মনোযোগ প্রয়োজন এমন বিষয় এবং এর অর্থ",
        "what_this_means": "এর অর্থ কী",
        "detected": "শনাক্ত হয়েছে",
        "all_pass_msg": "বিশ্লেষিত সমস্ত বিধিবদ্ধ প্যাকেজিং ঘোষণা স্বয়ংক্রিয় স্ক্রিনিং মানদণ্ড পূরণ করে। কোনো বিষয়ে অবিলম্বে মনোযোগের প্রয়োজন নেই।",
        "automated_score_note": "এই স্কোরটি স্বয়ংক্রিয় স্ক্রিনিং স্কোর। এটি কোনো অফিসিয়াল আইনি সম্মতির শতাংশ বা প্রয়োগ নির্ধারণ নয়।",
        "manual_score_note": "এই স্ক্রিনিংটি ভোক্তার দেওয়া তথ্যের ওপর ভিত্তি করে করা হয়েছে। এই প্রতিবেদনের কিছু তথ্য স্বাধীনভাবে যাচাই করা হয়নি।",
        "package_information_summary": "প্যাকেজ তথ্য সারাংশ",
        "marketed_by": "বিপণনকারীর বিবরণ",
        "best_before_shelf_life": "ব্যবহারের শেষ তারিখ / শেলফ লাইফ",
        "batch_lot_number": "ব্যাচ / লট নম্বর",
        "readability_title": "শারীরিক পাঠযোগ্যতা এবং পরিমাণ ঘোষণা মূল্যায়ন",
        "readability_score_tier": "দৃশ্যমান পাঠযোগ্যতা স্কোর ও স্তর",
        "net_qty_font_height": "আনুমানিক নেট পরিমাণ ফন্ট উচ্চতা",
        "min_required_font_height": "সর্বনিম্ন প্রয়োজনীয় বিধিবদ্ধ উচ্চতা",
        "rule_12_verdict": "নিয়ম ১২ স্ক্রিনিং রায়",
        "measurement_method": "পরিমাপ পদ্ধতি এবং অপটিক্যাল স্কেল",
        "assessment_summary": "মূল্যায়ন সারাংশ",
        "rule12_notice": "আনুমানিক পরিমাপ ডিজিটাল ছবি বিশ্লেষণ থেকে প্রাপ্ত। এগুলিকে কোনো ক্যালিব্রেটেড সার্টিফিকেট হিসেবে গণ্য করা উচিত নয়।",
        "no_img_msg": "এই ম্যানুয়াল পরীক্ষার জন্য প্যাকেজ আর্টওয়ার্ক জমা দেওয়া হয়নি। শারীরিক পাঠযোগ্যতা মূল্যায়ন করা হয়নি।",
        "external_verification_title": "বহিরাগত রেজিস্ট্রি যাচাইকরণ ও ক্রস-চেক",
        "overall_cross_check_status": "সামগ্রিক ক্রস-চেক অবস্থা",
        "verification_confidence_tier": "যাচাইকরণ নির্ভরযোগ্যতার স্তর",
        "authoritative_verdict": "অনুমোদিত রায়",
        "verification_sources": "যাচাইকরণ উৎস",
        "cross_check_target": "যাচাইকরণের লক্ষ্য",
        "extracted_value": "প্রাপ্ত মান",
        "registry_record": "রেজিস্ট্রি রেকর্ড",
        "human_review_title": "মানব কর্মকর্তা অডিট পর্যালোচনা",
        "review_workflow_status": "পর্যালোচনা কর্মপ্রবাহ অবস্থা",
        "assigned_officer": "নিযুক্ত আইনি পরিমাপবিজ্ঞান কর্মকর্তা",
        "verified_by_officer": "কর্মকর্তা দ্বারা যাচাইকৃত",
        "verification_timestamp": "যাচাইকরণের সময়মুদ্রা",
        "final_human_verdict": "চূড়ান্ত মানব সম্মতি রায়",
        "human_verified_score": "মানব যাচাইকৃত স্কোর",
        "ai_vs_human_delta": "AI বনাম মানব স্কোর পার্থক্য",
        "officer_notes": "কর্মকর্তার মন্তব্য",
        "detailed_compliance_checklist": "বিস্তারিত বিধিবদ্ধ সম্মতি চেকলিস্ট",
        "legal_metrology_title": "লিগ্যাল মেট্রোলজি (প্যাকেজড কমোডিটিজ) রুলস ২০১১",
        "fssai_title": "FSSAI (খাদ্য নিরাপত্তা ও মান লেবেলিং প্রবিধান)",
        "field_header": "নিয়ম আইডি",
        "requirement_header": "বিধিবদ্ধ প্রয়োজনীয়তা",
        "status_header": "অবস্থা",
        "detected_value_header": "সনাক্ত ঘোষণা",
        "finding_header": "আইনি ফলাফল",
        "evidence": "প্রমাণ",
        "location_header": "অবস্থান",
        "confidence_header": "বিশ্বাসযোগ্যতা",
        "recommended_check": "প্রস্তাবিত পরীক্ষা",
        "recommended_actions_title": "প্রস্তাবিত পরবর্তী পদক্ষেপ",
        "priority_header": "অগ্রাধিকার",
        "rule_title_header": "নিয়ম ও শিরোনাম",
        "issue_header": "চিহ্নিত সমস্যা",
        "recommended_action_header": "প্রস্তাবিত ব্যবস্থা",
        "statutory_basis_header": "বিধিবদ্ধ ভিত্তি",
        "no_rec_msg": "স্বয়ংক্রিয় স্ক্রিনিংয়ের ওপর ভিত্তি করে কোনো সংশোধনমূলক ব্যবস্থার প্রয়োজন নেই।",
        "visual_evidence_title": "দৃশ্যমান প্রমাণ পরিশিষ্ট",
        "security_integrity_title": "নিরাপত্তা, অখণ্ডতা ও অডিট উৎস",
        "integrity_hash_label": "ক্রিপ্টোগ্রাফিক অখণ্ডতা হ্যাশ (SHA-256)",
        "software_version_label": "সিস্টেম সফটওয়্যার সংস্করণ",
        "ruleset_version_label": "বিধিবদ্ধ রুলসেট সংস্করণ",
        "ocr_engine_label": "OCR ও ভিশন ইঞ্জিন",
        "audit_status_label": "অডিট যাচাইকরণ অবস্থা",
        "verification_notice_label": "যাচাইকরণ বিজ্ঞপ্তি",
        "evidence_summary": "প্রমাণ শৃঙ্খলা সারাংশ",
        "page": "পৃষ্ঠা",
        "disclaimer": "মেট্রচেক এআই বিশ্লেষণের জন্য জমা দেওয়া ছবির ওপর ভিত্তি করে স্ক্রিনিং প্রদান করে। ফলাফল অফিসিয়াল প্রয়োগ নির্ধারণ হিসেবে গণ্য নয়।",
    },
    "gu": {
        "report_title": "AI-સહાયિત ઉત્પાદન અનુપાલન સ્ક્રીનીંગ અહેવાલ",
        "subtitle": "ગ્રાહક બાબતોનો વિભાગ, ભારત સરકાર",
        "overall_status": "કાનૂની અનુપાલન સ્ક્રીનીંગ પરિણામ",
        "compliance_score": "અનુપાલન સ્કોર",
        "screening_score": "સ્ક્રીનીંગ સ્કોર",
        "product_name": "ઉત્પાદનનું નામ",
        "brand": "બ્રાન્ડ",
        "analysis_id": "વિશ્લેષણ ID",
        "analysis_mode": "વિશ્લેષણ મોડ",
        "manual_mode": "મેન્યુઅલ ઉત્પાદન તપાસ",
        "image_mode": "AI ઇમેજ અને OCR સ્ક્રીનીંગ",
        "info_source": "માહિતી સ્ત્રોત",
        "manual_source": "ગ્રાહક દ્વારા પૂરી પાડવામાં આવેલી ઘોષણાઓ",
        "image_source": "પેકેજ આર્ટવર્ક OCR અને કોમ્પ્યુટર વિઝન",
        "inspection_timestamp": "તપાસ સમય",
        "generated_at": "અહેવાલ બનાવ્યા સમય",
        "product_risk_tier": "ઉત્પાદન જોખમ સ્તર",
        "images_analyzed": "વિશ્લેષિત છબીઓ",
        "detected_languages": "શોધાયેલ પેકેજિંગ ભાષાઓ",
        "statutory_declarations": "કાનૂની ઘોષણાઓ (નિયમ ૬)",
        "executive_summary": "કાર્યકારી સારાંશ અને ઉત્પાદન ઝાંખી",
        "legal_disclaimer": "કાનૂની અસ્વીકરણ અને કાયદાકીય અવકાશ",
        "items_requiring_attention": "ધ્યાન આપવા યોગ્ય બાબતો અને તેનો અર્થ",
        "what_this_means": "આનો અર્થ શું છે",
        "detected": "શોધાયેલ",
        "all_pass_msg": "વિશ્લેષિત તમામ કાનૂની પેકેજિંગ ઘોષણાઓ સ્ક્રીનીંગ માપદંડોને પૂર્ણ કરે છે. કોઈ તાત્કાલિક પગલાંની જરૂર નથી.",
        "automated_score_note": "આ સ્કોર એક વેઇટેડ ઓટોમેટેડ સ્ક્રીનીંગ સ્કોર છે. તે કોઈ સત્તાવાર કાનૂની અમલીકરણ નિર્ધારણ નથી.",
        "manual_score_note": "આ સ્ક્રીનીંગ ગ્રાહક દ્વારા આપવામાં આવેલી વિગતો પર આધારિત છે. કેટલીક માહિતી સ્વતંત્ર રીતે ચકાસાયેલ નથી.",
        "package_information_summary": "પેકેજ માહિતી સારાંશ",
        "marketed_by": "માર્કેટિંગ કરનારની વિગતો",
        "best_before_shelf_life": "ઉપયોગની અંતિમ તારીખ / શેલ્ફ લાઇફ",
        "batch_lot_number": "બેચ / લોટ નંબર",
        "readability_title": "ભૌતિક વાંચનક્ષમતા અને જથ્થાની ઘોષણા મૂલ્યાંકન",
        "readability_score_tier": "વાંચનક્ષમતા સ્કોર અને સ્તર",
        "net_qty_font_height": "અંદાજિત ચોખ્ખો જથ્થો ફોન્ટ ઊંચાઈ",
        "min_required_font_height": "ન્યૂનતમ જરૂરી કાનૂની ઊંચાઈ",
        "rule_12_verdict": "નિયમ ૧૨ સ્ક્રીનીંગ નિર્ણય",
        "measurement_method": "માપન પદ્ધતિ અને ઓપ્ટિકલ સ્કેલ",
        "assessment_summary": "મૂલ્યાંકન સારાંશ",
        "rule12_notice": "અંદાજિત માપ ડિજિટલ ઇમેજ વિશ્લેષણમાંથી લેવામાં આવ્યા છે. તેને કેલિબ્રેટેડ પ્રમાણપત્ર ગણવું નહીં.",
        "no_img_msg": "આ મેન્યુઅલ તપાસ માટે પેકેજ આર્ટવર્ક સબમિટ કરવામાં આવ્યું ન હતું. ભૌતિક વાંચનક્ષમતાનું મૂલ્યાંકન થયું નથી.",
        "external_verification_title": "બાહ્ય રજિસ્ટ્રી ચકાસણી અને ક્રોસ-ચેકિંગ",
        "overall_cross_check_status": "એકંદર ક્રોસ-ચેક સ્થિતિ",
        "verification_confidence_tier": "ચકાસણી વિશ્વસનીયતા સ્તર",
        "authoritative_verdict": "સત્તાવાર નિર્ણય",
        "verification_sources": "ચકાસણી સ્ત્રોતો",
        "cross_check_target": "ચકાસણી લક્ષ્ય",
        "extracted_value": "મેળવેલ મૂલ્ય",
        "registry_record": "રજિસ્ટ્રી રેકોર્ડ",
        "human_review_title": "માનવ અધિકારી ઓડિટ સમીક્ષા",
        "review_workflow_status": "સમીક્ષા કાર્યપ્રવાહ સ્થિતિ",
        "assigned_officer": "નિયુક્ત કાનૂની મેટ્રોલોજી અધિકારી",
        "verified_by_officer": "અધિકારી દ્વારા ચકાસાયેલ",
        "verification_timestamp": "ચકાસણી સમયમુદ્રા",
        "final_human_verdict": "અંતિમ માનવ અનુપાલન નિર્ણય",
        "human_verified_score": "માનવ ચકાસાયેલ સ્કોર",
        "ai_vs_human_delta": "AI વિરુદ્ધ માનવ સ્કોર તફાવત",
        "officer_notes": "અધિકારી સમીક્ષા નોંધો",
        "detailed_compliance_checklist": "વિગતવાર કાનૂની અનુપાલન ચેકલિસ્ટ",
        "legal_metrology_title": "કાનૂની મેટ્રોલોજી (પેકેજ્ડ કોમોડિટીઝ) નિયમો ૨૦૧૧",
        "fssai_title": "FSSAI (ખાદ્ય સુરક્ષા અને ધોરણો લેબલીંગ નિયમો)",
        "field_header": "નિયમ ID",
        "requirement_header": "કાનૂની જરૂરિયાત",
        "status_header": "સ્થિતિ",
        "detected_value_header": "શોધાયેલ ઘોષણા",
        "finding_header": "કાનૂની તારણ",
        "evidence": "પુરાવો",
        "location_header": "સ્થાન",
        "confidence_header": "વિશ્વાસ",
        "recommended_check": "ભલામણ કરેલ તપાસ",
        "recommended_actions_title": "ભલામણ કરેલ આગલા પગલાં",
        "priority_header": "પ્રાથમિકતા",
        "rule_title_header": "નિયમ અને શીર્ષક",
        "issue_header": "ઓળખાયેલ સમસ્યા",
        "recommended_action_header": "ભલામણ કરેલ પગલાં",
        "statutory_basis_header": "કાનૂની આધાર",
        "no_rec_msg": "ઓટોમેટેડ સ્ક્રીનીંગના આધારે કોઈ સુધારાત્મક પગલાંની જરૂર નથી.",
        "visual_evidence_title": "દ્રશ્ય પુરાવા પરિશિષ્ટ",
        "security_integrity_title": "સુરક્ષા, અખંડિતતા અને ઓડિટ સ્ત્રોત",
        "integrity_hash_label": "ક્રિપ્ટોગ્રાફિક ઇન્ટિગ્રિટી હેશ (SHA-256)",
        "software_version_label": "સિસ્ટમ સોફ્ટવેર સંસ્કરણ",
        "ruleset_version_label": "કાનૂની રૂલસેટ સંસ્કરણ",
        "ocr_engine_label": "OCR અને વિઝન એન્જિન",
        "audit_status_label": "ઓડિટ ચકાસણી સ્થિતિ",
        "verification_notice_label": "ચકાસણી નોટિસ",
        "evidence_summary": "પુરાવા શૃંખલા સારાંશ",
        "page": "પૃષ્ઠ",
        "disclaimer": "મેટ્રચેક AI વિશ્લેષણ માટે સબમિટ કરેલી છબીઓના આધારે સ્ક્રીનીંગ પૂરું પાડે છે. પરિણામો સત્તાવાર અમલીકરણ નિર્ધારણ નથી.",
    },
    "pa": {
        "report_title": "AI-ਸਹਾਇਤਾ ਪ੍ਰਾਪਤ ਉਤਪਾਦ ਪਾਲਣਾ ਸਕ੍ਰੀਨਿੰਗ ਰਿਪੋਰਟ",
        "subtitle": "ਖਪਤਕਾਰ ਮਾਮਲੇ ਵਿਭਾਗ, ਭਾਰਤ ਸਰਕਾਰ",
        "overall_status": "ਕਾਨੂੰਨੀ ਪਾਲਣਾ ਸਕ੍ਰੀਨਿੰਗ ਨਤੀਜਾ",
        "compliance_score": "ਪਾਲਣਾ ਸਕੋਰ",
        "screening_score": "ਸਕ੍ਰੀਨਿੰਗ ਸਕੋਰ",
        "product_name": "ਉਤਪਾਦ ਦਾ ਨਾਮ",
        "brand": "ਬ੍ਰਾਂਡ",
        "analysis_id": "ਵਿਸ਼ਲੇਸ਼ਣ ID",
        "analysis_mode": "ਵਿਸ਼ਲੇਸ਼ਣ ਮੋਡ",
        "manual_mode": "ਦਸਤੀ ਉਤਪਾਦ ਜਾਂਚ",
        "image_mode": "AI ਚਿੱਤਰ ਅਤੇ OCR ਸਕ੍ਰੀਨਿੰਗ",
        "info_source": "ਜਾਣਕਾਰੀ ਸਰੋਤ",
        "manual_source": "ਖਪਤਕਾਰ ਦੁਆਰਾ ਪ੍ਰਦਾਨ ਕੀਤੀਆਂ ਗਈਆਂ ਘੋਸ਼ਣਾਵਾਂ",
        "image_source": "ਪੈਕੇਜ ਆਰਟਵਰਕ OCR ਅਤੇ ਕੰਪਿਊਟਰ ਵਿਜ਼ਨ",
        "inspection_timestamp": "ਨਿਰੀਖਣ ਸਮਾਂ",
        "generated_at": "ਰਿਪੋਰਟ ਤਿਆਰੀ ਸਮਾਂ",
        "product_risk_tier": "ਉਤਪਾਦ ਜੋਖਮ ਪੱਧਰ",
        "images_analyzed": "ਵਿਸ਼ਲੇਸ਼ਣ ਕੀਤੀਆਂ ਤਸਵੀਰਾਂ",
        "detected_languages": "ਲੱਭੀਆਂ ਗਈਆਂ ਪੈਕੇਜਿੰਗ ਭਾਸ਼ਾਵਾਂ",
        "statutory_declarations": "ਕਾਨੂੰਨੀ ਘੋਸ਼ਣਾਵਾਂ (ਨਿਯਮ 6)",
        "executive_summary": "ਕਾਰਜਕਾਰੀ ਸੰਖੇਪ ਅਤੇ ਉਤਪਾਦ ਜਾਣ-ਪਛਾਣ",
        "legal_disclaimer": "ਕਾਨੂੰਨੀ ਬੇਦਾਅਵਾ ਅਤੇ ਕਾਨੂੰਨੀ ਦਾਇਰਾ",
        "items_requiring_attention": "ਧਿਆਨ ਦੇਣ ਯੋਗ ਨੁਕਤੇ ਅਤੇ ਉਹਨਾਂ ਦਾ ਅਰਥ",
        "what_this_means": "ਇਸਦਾ ਕੀ ਅਰਥ ਹੈ",
        "detected": "ਲੱਭਿਆ ਗਿਆ",
        "all_pass_msg": "ਸਾਰੀਆਂ ਕਾਨੂੰਨੀ ਪੈਕੇਜਿੰਗ ਘੋਸ਼ਣਾਵਾਂ ਸਕ੍ਰੀਨਿੰਗ ਮਾਪਦੰਡਾਂ ਨੂੰ ਪੂਰਾ ਕਰਦੀਆਂ ਹਨ। ਤੁਰੰਤ ਧਿਆਨ ਦੇਣ ਦੀ ਲੋੜ ਨਹੀਂ ਹੈ।",
        "automated_score_note": "ਇਹ ਸਕੋਰ ਆਟੋਮੇਟਿਡ ਸਕ੍ਰੀਨਿੰਗ ਸਕੋਰ ਹੈ। ਇਹ ਕੋਈ ਅਧਿਕਾਰਤ ਕਾਨੂੰਨੀ ਪਾਲਣਾ ਪ੍ਰਤੀਸ਼ਤ ਨਹੀਂ ਹੈ।",
        "manual_score_note": "ਇਹ ਸਕ੍ਰੀਨਿੰਗ ਖਪਤਕਾਰ ਦੁਆਰਾ ਦਿੱਤੀ ਗਈ ਜਾਣਕਾਰੀ 'ਤੇ ਆਧਾਰਿਤ ਹੈ। ਕੁਝ ਜਾਣਕਾਰੀ ਸੁਤੰਤਰ ਤੌਰ 'ਤੇ ਤਸਦੀਕ ਨਹੀਂ ਕੀਤੀ ਗਈ ਸੀ।",
        "package_information_summary": "ਪੈਕੇਜ ਜਾਣਕਾਰੀ ਸੰਖੇਪ",
        "marketed_by": "ਮਾਰਕੀਟਿੰਗ ਵੇਰਵਾ",
        "best_before_shelf_life": "ਵਰਤੋਂ ਦੀ ਆਖਰੀ ਮਿਤੀ / ਸ਼ੈਲਫ ਲਾਈਫ",
        "batch_lot_number": "ਬੈਚ / ਲਾਟ ਨੰਬਰ",
        "readability_title": "ਸਰੀਰਕ ਪੜ੍ਹਨਯੋਗਤਾ ਅਤੇ ਮਾਤਰਾ ਘੋਸ਼ਣਾ ਮੁਲਾਂਕਣ",
        "readability_score_tier": "ਦ੍ਰਿਸ਼ਟੀਗਤ ਪੜ੍ਹਨਯੋਗਤਾ ਸਕੋਰ ਅਤੇ ਪੱਧਰ",
        "net_qty_font_height": "ਅੰਦਾਜ਼ਨ ਸ਼ੁੱਧ ਮਾਤਰਾ ਫੌਂਟ ਉਚਾਈ",
        "min_required_font_height": "ਘੱਟੋ-ਘੱਟ ਲੋੜੀਂਦੀ ਕਾਨੂੰਨੀ ਉਚਾਈ",
        "rule_12_verdict": "ਨਿਯਮ 12 ਸਕ੍ਰੀਨਿੰਗ ਫੈਸਲਾ",
        "measurement_method": "ਮਾਪਣ ਦਾ ਤਰੀਕਾ ਅਤੇ ਆਪਟੀਕਲ ਸਕੇਲ",
        "assessment_summary": "ਮੁਲਾਂਕਣ ਸੰਖੇਪ",
        "rule12_notice": "ਅੰਦਾਜ਼ਨ ਮਾਪ ਡਿਜੀਟਲ ਚਿੱਤਰ ਵਿਸ਼ਲੇਸ਼ਣ ਤੋਂ ਲਏ ਗਏ ਹਨ। ਇਹਨਾਂ ਨੂੰ ਕੈਲੀਬਰੇਟ ਕੀਤਾ ਸਰਟੀਫਿਕੇਟ ਨਹੀਂ ਮੰਨਿਆ ਜਾਣਾ ਚਾਹੀਦਾ।",
        "no_img_msg": "ਇਸ ਦਸਤੀ ਜਾਂਚ ਲਈ ਪੈਕੇਜ ਆਰਟਵਰਕ ਜਮ੍ਹਾਂ ਨਹੀਂ ਕੀਤਾ ਗਿਆ ਸੀ। ਸਰੀਰਕ ਪੜ੍ਹਨਯੋਗਤਾ ਦਾ ਮੁਲਾਂਕਣ ਨਹੀਂ ਕੀਤਾ ਗਿਆ।",
        "external_verification_title": "ਬਾਹਰੀ ਰਜਿਸਟਰੀ ਤਸਦੀਕ ਅਤੇ ਕਰਾਸ-ਜਾਂਚ",
        "overall_cross_check_status": "ਸਮੁੱਚੀ ਕਰਾਸ-ਜਾਂਚ ਸਥਿਤੀ",
        "verification_confidence_tier": "ਤਸਦੀਕ ਭਰੋਸੇਯੋਗਤਾ ਪੱਧਰ",
        "authoritative_verdict": "ਅਧਿਕਾਰਤ ਫੈਸਲਾ",
        "verification_sources": "ਤਸਦੀਕ ਸਰੋਤ",
        "cross_check_target": "ਤਸਦੀਕ ਨਿਸ਼ਾਨਾ",
        "extracted_value": "ਪ੍ਰਾਪਤ ਮੁੱਲ",
        "registry_record": "ਰਜਿਸਟਰੀ ਰਿਕਾਰਡ",
        "human_review_title": "ਮਨੁੱਖੀ ਅਧਿਕਾਰੀ ਆਡਿਟ ਸਮੀਖਿਆ",
        "review_workflow_status": "ਸਮੀਖਿਆ ਵਰਕਫਲੋ ਸਥਿਤੀ",
        "assigned_officer": "ਨਿਯੁਕਤ ਕਾਨੂੰਨੀ ਮੈਟਰੋਲੋਜੀ ਅਧਿਕਾਰੀ",
        "verified_by_officer": "ਅਧਿਕਾਰੀ ਦੁਆਰਾ ਤਸਦੀਕ ਕੀਤਾ",
        "verification_timestamp": "ਤਸਦੀਕ ਸਮਾਂ ਮੋਹਰ",
        "final_human_verdict": "ਅੰਤਿਮ ਮਨੁੱਖੀ ਪਾਲਣਾ ਫੈਸਲਾ",
        "human_verified_score": "ਮਨੁੱਖੀ ਤਸਦੀਕਸ਼ੁਦਾ ਸਕੋਰ",
        "ai_vs_human_delta": "AI ਬਨਾਮ ਮਨੁੱਖੀ ਸਕੋਰ ਅੰਤਰ",
        "officer_notes": "ਅਧਿਕਾਰੀ ਸਮੀਖਿਆ ਨੋਟਸ",
        "detailed_compliance_checklist": "ਵਿਸਤ੍ਰਿਤ ਕਾਨੂੰਨੀ ਪਾਲਣਾ ਚੈੱਕਲਿਸਟ",
        "legal_metrology_title": "ਕਾਨੂੰਨੀ ਮੈਟਰੋਲੋਜੀ (ਪੈਕਡ ਵਸਤੂਆਂ) ਨਿਯਮ 2011",
        "fssai_title": "FSSAI (ਭੋਜਨ ਸੁਰੱਖਿਆ ਅਤੇ ਮਿਆਰ ਲੇਬਲਿੰਗ ਨਿਯਮ)",
        "field_header": "ਨਿਯਮ ID",
        "requirement_header": "ਕਾਨੂੰਨੀ ਲੋੜ",
        "status_header": "ਸਥਿਤੀ",
        "detected_value_header": "ਲੱਭੀ ਗਈ ਘੋਸ਼ਣਾ",
        "finding_header": "ਕਾਨੂੰਨੀ ਨਤੀਜਾ",
        "evidence": "ਸਬੂਤ",
        "location_header": "ਸਥਾਨ",
        "confidence_header": "ਭਰੋਸਾ",
        "recommended_check": "ਸਿਫਾਰਸ਼ ਕੀਤੀ ਜਾਂਚ",
        "recommended_actions_title": "ਸਿਫਾਰਸ਼ ਕੀਤੀਆਂ ਅਗਲੀਆਂ ਕਾਰਵਾਈਆਂ",
        "priority_header": "ਤਰਜੀਹ",
        "rule_title_header": "ਨਿਯਮ ਅਤੇ ਸਿਰਲੇਖ",
        "issue_header": "ਪਛਾਣੀ ਗਈ ਸਮੱਸਿਆ",
        "recommended_action_header": "ਸਿਫਾਰਸ਼ ਕੀਤੀ ਕਾਰਵਾਈ",
        "statutory_basis_header": "ਕਾਨੂੰਨੀ ਆਧਾਰ",
        "no_rec_msg": "ਆਟੋਮੇਟਿਡ ਸਕ੍ਰੀਨਿੰਗ ਦੇ ਆਧਾਰ 'ਤੇ ਕਿਸੇ ਸੁਧਾਰਾਤਮਕ ਕਾਰਵਾਈ ਦੀ ਲੋੜ ਨਹੀਂ ਹੈ।",
        "visual_evidence_title": "ਵਿਜ਼ੂਅਲ ਸਬੂਤ ਅੰਤਿਕਾ",
        "security_integrity_title": "ਸੁਰੱਖਿਆ, ਅਖੰਡਤਾ ਅਤੇ ਆਡਿਟ ਮੂਲ",
        "integrity_hash_label": "ਕ੍ਰਿਪਟੋਗ੍ਰਾਫਿਕ ਇੰਟੀਗ੍ਰਿਟੀ ਹੈਸ਼ (SHA-256)",
        "software_version_label": "ਸਿਸਟਮ ਸਾਫਟਵੇਅਰ ਸੰਸਕਰਣ",
        "ruleset_version_label": "ਕਾਨੂੰਨੀ ਰੂਲਸੈੱਟ ਸੰਸਕਰਣ",
        "ocr_engine_label": "OCR ਅਤੇ ਵਿਜ਼ਨ ਇੰਜਨ",
        "audit_status_label": "ਆਡਿਟ ਤਸਦੀਕ ਸਥਿਤੀ",
        "verification_notice_label": "ਤਸਦੀਕ ਨੋਟਿਸ",
        "evidence_summary": "ਸਬੂਤ ਲੜੀ ਸੰਖੇਪ",
        "page": "ਸਫ਼ਾ",
        "disclaimer": "ਮੈਟ੍ਰਚੈੱਕ ਏਆਈ ਵਿਸ਼ਲੇਸ਼ਣ ਲਈ ਜਮ੍ਹਾਂ ਕੀਤੀਆਂ ਤਸਵੀਰਾਂ ਦੇ ਆਧਾਰ 'ਤੇ ਸਕ੍ਰੀਨਿੰਗ ਪ੍ਰਦਾਨ ਕਰਦਾ ਹੈ। ਨਤੀਜੇ ਅਧਿਕਾਰਤ ਕਾਨੂੰਨੀ ਲਾਗੂਕਰਨ ਨਿਰਧਾਰਨ ਨਹੀਂ ਹਨ।",
    },
    "ta": {
        "report_title": "AI-உதவி தயாரிப்பு இணக்க திரையிடல் அறிக்கை",
        "subtitle": "நுகர்வோர் விவகாரங்கள் துறை, இந்திய அரசு",
        "overall_status": "சட்டப்பூர்வ இணக்க திரையிடல் முடிவு",
        "compliance_score": "இணக்க மதிப்பெண்",
        "screening_score": "திரையிடல் மதிப்பெண்",
        "product_name": "தயாரிப்பு பெயர்",
        "brand": "பிராண்ட்",
        "analysis_id": "பகுப்பாய்வு ID",
        "analysis_mode": "பகுப்பாய்வு முறை",
        "manual_mode": "கையேடு தயாரிப்பு சரிபார்ப்பு",
        "image_mode": "AI படம் மற்றும் OCR திரையிடல்",
        "info_source": "தகவல் ஆதாரம்",
        "manual_source": "நுகர்வோரால் வழங்கப்பட்ட அறிவிப்புகள்",
        "image_source": "பேக்கேஜ் ஆர்ட்வொர்க் OCR மற்றும் கம்ப்யூட்டர் விஷன்",
        "inspection_timestamp": "ஆய்வு நேரம்",
        "generated_at": "அறிக்கை உருவாக்கப்பட்ட நேரம்",
        "product_risk_tier": "தயாரிப்பு அபாய நிலை",
        "images_analyzed": "பகுப்பாய்வு செய்யப்பட்ட படங்கள்",
        "detected_languages": "கண்டறியப்பட்ட பேக்கேஜிங் மொழிகள்",
        "statutory_declarations": "சட்டப்பூர்வ அறிவிப்புகள் (விதி 6)",
        "executive_summary": "நிர்வாக சுருக்கம் மற்றும் தயாரிப்பு கண்ணோட்டம்",
        "legal_disclaimer": "சட்ட மறுப்பு மற்றும் சட்ட வரம்பு",
        "items_requiring_attention": "கவனம் தேவைப்படும் அம்சங்கள் மற்றும் அவற்றின் பொருள்",
        "what_this_means": "இதன் பொருள் என்ன",
        "detected": "கண்டறியப்பட்டது",
        "all_pass_msg": "அனைத்து சட்டப்பூர்வ பேக்கேஜிங் அறிவிப்புகளும் தானியங்கி திரையிடல் அளவுகோல்களை பூர்த்தி செய்கின்றன. உடனடி கவனம் தேவையில்லை.",
        "automated_score_note": "இந்த மதிப்பெண் தானியங்கி திரையிடல் மதிப்பெண் ஆகும். இது அதிகாரப்பூர்வ அமலாக்க நிர்ணயம் அல்ல.",
        "manual_score_note": "இந்தத் திரையிடல் நுகர்வோரால் வழங்கப்பட்ட தகவலை அடிப்படையாகக் கொண்டது. சில தகவல்கள் சுயாதீனமாக சரிபார்க்கப்படவில்லை.",
        "package_information_summary": "தொகுப்பு தகவல் சுருக்கம்",
        "marketed_by": "சந்தைப்படுத்துபவர் விவரம்",
        "best_before_shelf_life": "பயன்படுத்துவதற்கான கடைசி தேதி / அடுக்கு வாழ்க்கை",
        "batch_lot_number": "தொகுதி / லாட் எண்",
        "readability_title": "படிக்கக்கூடிய தன்மை மற்றும் அளவு அறிவிப்பு மதிப்பீடு",
        "readability_score_tier": "படிக்கக்கூடிய தன்மை மதிப்பெண் மற்றும் நிலை",
        "net_qty_font_height": "மதிப்பிடப்பட்ட நிகர அளவு எழுத்துரு உயரம்",
        "min_required_font_height": "குறைந்தபட்ச தேவையான சட்டப்பூர்வ உயரம்",
        "rule_12_verdict": "விதி 12 திரையிடல் தீர்ப்பு",
        "measurement_method": "அளவீட்டு முறை மற்றும் ஆப்டிகல் அளவுகோல்",
        "assessment_summary": "மதிப்பீட்டு சுருக்கம்",
        "rule12_notice": "மதிப்பிடப்பட்ட அளவீடுகள் டிஜிட்டல் பட பகுப்பாய்விலிருந்து பெறப்பட்டவை. இவற்றை அளவீட்டு சான்றிதழாகக் கருதக்கூடாது.",
        "no_img_msg": "இந்த கையேடு ஆய்வுக்கு தொகுப்பு படங்கள் சமர்ப்பிக்கப்படவில்லை. உடல் வாசிப்புத்திறன் மதிப்பீடு செய்யப்படவில்லை.",
        "external_verification_title": "வெளிப்புற பதிவக சரிபார்ப்பு மற்றும் குறுக்கு சோதனை",
        "overall_cross_check_status": "ஒட்டுமொத்த குறுக்கு சரிபார்ப்பு நிலை",
        "verification_confidence_tier": "சரிபார்ப்பு நம்பகத்தன்மை நிலை",
        "authoritative_verdict": "அங்கீகரிக்கப்பட்ட தீர்ப்பு",
        "verification_sources": "சரிபார்ப்பு ஆதாரங்கள்",
        "cross_check_target": "சரிபார்ப்பு இலக்கு",
        "extracted_value": "பிரித்தெடுக்கப்பட்ட மதிப்பு",
        "registry_record": "பதிவேடு விவரம்",
        "human_review_title": "மனித அதிகாரி தணிக்கை மறுஆய்வு",
        "review_workflow_status": "மறுஆய்வு பணிப்பாய்வு நிலை",
        "assigned_officer": "ஒதுக்கப்பட்ட சட்ட அளவியல் அதிகாரி",
        "verified_by_officer": "அதிகாரியால் சரிபார்க்கப்பட்டது",
        "verification_timestamp": "சரிபார்ப்பு நேர முத்திரை",
        "final_human_verdict": "இறுதி மனித இணக்க தீர்ப்பு",
        "human_verified_score": "மனித சரிபார்க்கப்பட்ட மதிப்பெண்",
        "ai_vs_human_delta": "AI எதிர் மனித மதிப்பெண் வித்தியாசம்",
        "officer_notes": "அதிகாரி மறுஆய்வு குறிப்புகள்",
        "detailed_compliance_checklist": "விரிவான சட்டப்பூர்வ இணக்க சரிபார்ப்பு பட்டியல்",
        "legal_metrology_title": "சட்ட அளவியல் (பொட்டலமிடப்பட்ட பொருட்கள்) விதிகள் 2011",
        "fssai_title": "FSSAI (உணவு பாதுகாப்பு மற்றும் தரநிலைகள் லேபிளிங் விதிமுறைகள்)",
        "field_header": "விதி ID",
        "requirement_header": "சட்டப்பூர்வ தேவை",
        "status_header": "நிலை",
        "detected_value_header": "கண்டறியப்பட்ட அறிவிப்பு",
        "finding_header": "சட்ட முடிவு",
        "evidence": "சான்று",
        "location_header": "இடம்",
        "confidence_header": "நம்பகத்தன்மை",
        "recommended_check": "பரிந்துரைக்கப்பட்ட சரிபார்ப்பு",
        "recommended_actions_title": "பரிந்துரைக்கப்பட்ட அடுத்த படிகள்",
        "priority_header": "முன்னுரிமை",
        "rule_title_header": "விதி மற்றும் தலைப்பு",
        "issue_header": "கண்டறியப்பட்ட சிக்கல்",
        "recommended_action_header": "பரிந்துரைக்கப்பட்ட நடவடிக்கை",
        "statutory_basis_header": "சட்டப்பூர்வ அடிப்படை",
        "no_rec_msg": "தானியங்கி திரையிடலின் அடிப்படையில் திருத்த நடவடிக்கைகள் எதுவும் தேவையில்லை.",
        "visual_evidence_title": "காட்சி சான்று இணைப்பு",
        "security_integrity_title": "பாதுகாப்பு, ஒருமைப்பாடு மற்றும் தணிக்கை தோற்றம்",
        "integrity_hash_label": "கிரிப்டோகிராஃபிக் ஒருமைப்பாடு ஹாஷ் (SHA-256)",
        "software_version_label": "அமைப்பு மென்பொருள் பதிப்பு",
        "ruleset_version_label": "சட்ட விதித்தொகுப்பு பதிப்பு",
        "ocr_engine_label": "OCR மற்றும் பார்வை எஞ்சின்",
        "audit_status_label": "தணிக்கை சரிபார்ப்பு நிலை",
        "verification_notice_label": "சரிபார்ப்பு அறிவிப்பு",
        "evidence_summary": "சான்று சங்கிலி சுருக்கம்",
        "page": "பக்கம்",
        "disclaimer": "மெட்ர்ட்செக் AI பகுப்பாய்விற்கு சமர்ப்பிக்கப்பட்ட படங்களின் அடிப்படையில் திரையிடலை வழங்குகிறது. முடிவுகள் அதிகாரப்பூர்வ அமலாக்க தீர்மானம் அல்ல.",
    },
    "te": {
        "report_title": "AI-సహాయక ఉత్పత్తి సమ్మతి స్క్రీనింగ్ నివేదిక",
        "subtitle": "వినియోగదారుల వ్యవహారాల మంత్రిత్వ శాఖ, భారత ప్రభుత్వం",
        "overall_status": "చట్టబద్ధమైన సమ్మతి స్క్రీనింగ్ ఫలితం",
        "compliance_score": "సమ్మతి స్కోరు",
        "screening_score": "స్క్రీనింగ్ స్కోరు",
        "product_name": "ఉత్పత్తి పేరు",
        "brand": "బ్రాండ్",
        "analysis_id": "విశ్లేషణ ID",
        "analysis_mode": "విశ్లేషణ మోడ్",
        "manual_mode": "మాన్యువల్ ఉత్పత్తి తనిఖీ",
        "image_mode": "AI ఇమేజ్ మరియు OCR స్క్రీనింగ్",
        "info_source": "సమాచార మూలం",
        "manual_source": "వినియోగదారు అందించిన ప్రకటనలు",
        "image_source": "ప్యాకేజీ ఆర్ట్‌వర్క్ OCR మరియు కంప్యూటర్ విజన్",
        "inspection_timestamp": "తనిఖీ సమయం",
        "generated_at": "నివేదిక రూపొందించిన సమయం",
        "product_risk_tier": "ఉత్పత్తి ప్రమాద స్థాయి",
        "images_analyzed": "విశ్లేషించిన చిత్రాలు",
        "detected_languages": "గుర్తించిన ప్యాకేజింగ్ భాషలు",
        "statutory_declarations": "చట్టబద్ధమైన ప్రకటనలు (రూల్ 6)",
        "executive_summary": "ఎగ్జిక్యూటివ్ సారాంశం మరియు ఉత్పత్తి అవలోకనం",
        "legal_disclaimer": "చట్టపరమైన నిరాకరణ మరియు చట్టబద్ధమైన పరిధి",
        "items_requiring_attention": "శ్రద్ధ అవసరమైన అంశాలు మరియు వాటి అర్థం",
        "what_this_means": "దీని అర్థం ఏమిటి",
        "detected": "గుర్తించబడింది",
        "all_pass_msg": "విశ్లేషించిన అన్ని చట్టబద్ధమైన ప్యాకేజింగ్ ప్రకటనలు ఆటోమేటెడ్ స్క్రీనింగ్ ప్రమాణాలకు అనుగుణంగా ఉన్నాయి. తక్షణ శ్రద్ధ అవసరం లేదు.",
        "automated_score_note": "ఈ స్కోరు ఆటోమేటెడ్ స్క్రీనింగ్ స్కోరు. ఇది అధికారిక చట్టపరమైన అమలు నిర్ణయం కాదు.",
        "manual_score_note": "ఈ స్క్రీనింగ్ వినియోగదారు అందించిన సమాచారంపై ఆధారపడి ఉంటుంది. కొన్ని వివరాలు స్వతంత్రంగా ధృవీకరించబడలేదు.",
        "package_information_summary": "ప్యాకేజీ సమాచార సారాంశం",
        "marketed_by": "మార్కెటింగ్ వివరాలు",
        "best_before_shelf_life": "ఉత్తమ వినియోగ తేదీ / షెల్ఫ్ లైఫ్",
        "batch_lot_number": "బ్యాచ్ / లాట్ సంఖ్య",
        "readability_title": "భౌతిక చదవగలిగే సామర్థ్యం మరియు పరిమాణ ప్రకటన మూల్యాంకనం",
        "readability_score_tier": "చదవగలిగే సామర్థ్య స్కోరు మరియు స్థాయి",
        "net_qty_font_height": "అంచనా వేసిన నికర పరిమాణం ఫాంట్ ఎత్తు",
        "min_required_font_height": "కనిష్ట అవసరమైన చట్టబద్ధమైన ఎత్తు",
        "rule_12_verdict": "రూల్ 12 స్క్రీనింగ్ తీర్పు",
        "measurement_method": "కొలత పద్ధతి మరియు ఆప్టికల్ స్కేల్",
        "assessment_summary": "మూల్యాంకన సారాంశం",
        "rule12_notice": "అంచనా కొలతలు డిజిటల్ ఇమేజ్ విశ్లేషణ నుండి పొందబడ్డాయి. వీటిని క్యాలిబ్రేట్ చేసిన సర్టిఫికెట్‌గా పరిగణించరాదు.",
        "no_img_msg": "ఈ మాన్యువల్ తనిఖీ కోసం ప్యాకేజీ చిత్రాలు సమర్పించబడలేదు. భౌతిక రీడబిలిటీ మూల్యాంకనం చేయబడలేదు.",
        "external_verification_title": "బాహ్య రిజిస్ట్రీ ధృవీకరణ మరియు క్రాస్-చెకింగ్",
        "overall_cross_check_status": "మొత్తం క్రాస్-చెక్ స్థితి",
        "verification_confidence_tier": "ధృవీకరణ విశ్వసనీయత స్థాయి",
        "authoritative_verdict": "అధికారిక తీర్పు",
        "verification_sources": "ధృవీకరణ మూలాలు",
        "cross_check_target": "ధృవీకరణ లక్ష్యం",
        "extracted_value": "సేకరించిన విలువ",
        "registry_record": "రిజిస్ట్రీ రికార్డు",
        "human_review_title": "మానవ అధికారి ఆడిట్ సమీక్ష",
        "review_workflow_status": "సమీక్ష వర్క్‌ఫ్లో స్థితి",
        "assigned_officer": "కేటాయించిన లీగల్ మెట్రాలజీ అధికారి",
        "verified_by_officer": "అధికారి ద్వారా ధృవీకరించబడింది",
        "verification_timestamp": "ధృవీకరణ సమయ ముద్ర",
        "final_human_verdict": "తుది మానవ సమ్మతి తీర్పు",
        "human_verified_score": "మానవ ధృవీకరించిన స్కోరు",
        "ai_vs_human_delta": "AI వర్సెస్ మానవ స్కోరు వ్యత్యాసం",
        "officer_notes": "అధికారి సమీక్ష గమనికలు",
        "detailed_compliance_checklist": "వివరణాత్మక చట్టబద్ధమైన సమ్మతి చెక్‌లిస్ట్",
        "legal_metrology_title": "లీగల్ మెట్రాలజీ (ప్యాక్ చేసిన వస్తువులు) నియమాలు 2011",
        "fssai_title": "FSSAI (ఆహార భద్రత మరియు ప్రమాణాలు లేబులింగ్ నిబంధనలు)",
        "field_header": "నియమం ID",
        "requirement_header": "చట్టబద్ధమైన అవసరం",
        "status_header": "స్థితి",
        "detected_value_header": "గుర్తించిన ప్రకటన",
        "finding_header": "చట్టపరమైన ఫలితం",
        "evidence": "సాక్ష్యం",
        "location_header": "స్థానం",
        "confidence_header": "విశ్వసనీయత",
        "recommended_check": "సిఫార్సు చేసిన తనిఖీ",
        "recommended_actions_title": "సిఫార్సు చేయబడిన తదుపరి చర్యలు",
        "priority_header": "ప్రాధాన్యత",
        "rule_title_header": "నియమం మరియు శీర్షిక",
        "issue_header": "గుర్తించిన సమస్య",
        "recommended_action_header": "సిఫార్సు చేయబడిన చర్య",
        "statutory_basis_header": "చట్టబద్ధమైన ఆధారం",
        "no_rec_msg": "ఆటోమేటెడ్ స్క్రీనింగ్ ఆధారంగా ఎటువంటి దిద్దుబాటు చర్యలు అవసరం లేదు.",
        "visual_evidence_title": "దృశ్య ఆధారాల అనుబంధం",
        "security_integrity_title": "భద్రత, సమగ్రత మరియు ఆడిట్ మూలం",
        "integrity_hash_label": "క్రిప్టోగ్రాఫిక్ సమగ్రత హాష్ (SHA-256)",
        "software_version_label": "సిస్టమ్ సాఫ్ట్‌వేర్ వెర్షన్",
        "ruleset_version_label": "చట్టబద్ధమైన రూల్‌సెట్ వెర్షన్",
        "ocr_engine_label": "OCR మరియు విజన్ ఇంజిన్",
        "audit_status_label": "ఆడిట్ ధృవీకరణ స్థితి",
        "verification_notice_label": "ధృవీకరణ నోటీసు",
        "evidence_summary": "ఆధారాల శృంఖల సారాంశం",
        "page": "పేజీ",
        "disclaimer": "మెట్ర్‌చెక్ AI సమర్పించిన చిత్రాల ఆధారంగా స్క్రీనింగ్ అందిస్తుంది. ఫలితాలు అధికారిక అమలు నిర్ణయం కాదు.",
    },
    "kn": {
        "report_title": "AI-ಸಹಾಯಿತ ಉತ್ಪನ್ನ ಅನುಸರಣೆ ಸ್ಕ್ರೀನಿಂಗ್ ವರದಿ",
        "subtitle": "ಗ್ರಾಹಕ ವ್ಯವಹಾರಗಳ ಇಲಾಖೆ, ಭಾರತ ಸರ್ಕಾರ",
        "overall_status": "ಶಾಸನಬದ್ಧ ಅನುಸರಣೆ ಸ್ಕ್ರೀನಿಂಗ್ ಫಲಿತಾಂಶ",
        "compliance_score": "ಅನುಸರಣೆ ಸ್ಕೋರ್",
        "screening_score": "ಸ್ಕ್ರೀನಿಂಗ್ ಸ್ಕೋರ್",
        "product_name": "ಉತ್ಪನ್ನದ ಹೆಸರು",
        "brand": "ಬ್ರ್ಯಾಂಡ್",
        "analysis_id": "ವಿಶ್ಲೇಷಣೆ ID",
        "analysis_mode": "ವಿಶ್ಲೇಷಣೆ ಮೋಡ್",
        "manual_mode": "ಹಸ್ತಚಾಲಿತ ಉತ್ಪನ್ನ ತಪಾಸಣೆ",
        "image_mode": "AI ಇಮೇಜ್ ಮತ್ತು OCR ಸ್ಕ್ರೀನಿಂಗ್",
        "info_source": "ಮಾಹಿತಿ ಮೂಲ",
        "manual_source": "ಗ್ರಾಹಕರು ನೀಡಿದ ಘೋಷಣೆಗಳು",
        "image_source": "ಪ್ಯಾಕೇಜ್ ಕಲಾಕೃತಿ OCR ಮತ್ತು ಕಂಪ್ಯೂಟರ್ ದೃಷ್ಟಿ",
        "inspection_timestamp": "ತಪಾಸಣೆ ಸಮಯ",
        "generated_at": "ವರದಿ ರಚಿಸಿದ ಸಮಯ",
        "product_risk_tier": "ಉತ್ಪನ್ನ ಅಪಾಯದ ಮಟ್ಟ",
        "images_analyzed": "ವಿಶ್ಲೇಷಿಸಿದ ಚಿತ್ರಗಳು",
        "detected_languages": "ಗುರುತಿಸಲಾದ ಪ್ಯಾಕೇಜಿಂಗ್ ಭಾಷೆಗಳು",
        "statutory_declarations": "ಶಾಸನಬದ್ಧ ಘೋಷಣೆಗಳು (ನಿಯಮ 6)",
        "executive_summary": "ಕಾರ್ಯನಿರ್ವಾಹಕ ಸಾರಾಂಶ ಮತ್ತು ಉತ್ಪನ್ನ ಅವಲೋಕನ",
        "legal_disclaimer": "ಕಾನೂನು ಹಕ್ಕು ನಿರಾಕರಣೆ ಮತ್ತು ಶಾಸನಬದ್ಧ ವ್ಯಾಪ್ತಿ",
        "items_requiring_attention": "ಗಮನ ಹರಿಸಬೇಕಾದ ಅಂಶಗಳು ಮತ್ತು ಅವುಗಳ ಅರ್ಥ",
        "what_this_means": "ಇದರ ಅರ್ಥವೇನು",
        "detected": "ಗುರುತಿಸಲಾಗಿದೆ",
        "all_pass_msg": "ವಿಶ್ಲೇಷಿಸಿದ ಎಲ್ಲಾ ಶಾಸನಬದ್ಧ ಪ್ಯಾಕೇಜಿಂಗ್ ಘೋಷಣೆಗಳು ಸ್ಕ್ರೀನಿಂಗ್ ಮಾನದಂಡಗಳನ್ನು ಪೂರೈಸುತ್ತವೆ. ತಕ್ಷಣದ ಗಮನ ಅಗತ್ಯವಿಲ್ಲ.",
        "automated_score_note": "ಈ ಸ್ಕೋರ್ ಸ್ವಯಂಚಾಲಿತ ಸ್ಕ್ರೀನಿಂಗ್ ಸ್ಕೋರ್ ಆಗಿದೆ. ಇದು ಅಧಿಕೃತ ಕಾನೂನು ಜಾರಿ ನಿರ್ಧಾರವಲ್ಲ.",
        "manual_score_note": "ಈ ಸ್ಕ್ರೀನಿಂಗ್ ಗ್ರಾಹಕರು ಒದಗಿಸಿದ ಮಾಹಿತಿಯನ್ನು ಆಧರಿಸಿದೆ. ಕೆಲವು ಮಾಹಿತಿಯನ್ನು ಸ್ವತಂತ್ರವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿಲ್ಲ.",
        "package_information_summary": "ಪ್ಯಾಕೇಜ್ ಮಾಹಿತಿ ಸಾರಾಂಶ",
        "marketed_by": "ಮಾರುಕಟ್ಟೆದಾರರ ವಿವರಗಳು",
        "best_before_shelf_life": "ಬಳಸಲು ಕೊನೆಯ ದಿನಾಂಕ / ಶೆಲ್ಫ್ ಲೈಫ್",
        "batch_lot_number": "ಬ್ಯಾಚ್ / ಲಾಟ್ ಸಂಖ್ಯೆ",
        "readability_title": "ಭೌತಿಕ ಓದುವಿಕೆ ಮತ್ತು ಪ್ರಮಾಣ ಘೋಷಣೆ ಮೌಲ್ಯಮಾಪನ",
        "readability_score_tier": "ಓದುವ ಸಾಮರ್ಥ್ಯದ ಸ್ಕೋರ್ ಮತ್ತು ಶ್ರೇಣಿ",
        "net_qty_font_height": "ಅಂದಾಜು ನಿವ್ವಳ ಪ್ರಮಾಣ ಫಾಂಟ್ ಎತ್ತರ",
        "min_required_font_height": "ಕನಿಷ್ಠ ಅಗತ್ಯವಿರುವ ಶಾಸನಬದ್ಧ ಎತ್ತರ",
        "rule_12_verdict": "ನಿಯಮ 12 ಸ್ಕ್ರೀನಿಂಗ್ ತೀರ್ಪು",
        "measurement_method": "ಅಳತೆ ವಿಧಾನ ಮತ್ತು ಆಪ್ಟಿಕಲ್ ಸ್ಕೇಲ್",
        "assessment_summary": "ಮೌಲ್ಯಮಾಪನ ಸಾರಾಂಶ",
        "rule12_notice": "ಅಂದಾಜು ಅಳತೆಗಳನ್ನು ಡಿಜಿಟಲ್ ಚಿತ್ರ ವಿಶ್ಲೇಷಣೆಯಿಂದ ಪಡೆಯಲಾಗಿದೆ. ಇವುಗಳನ್ನು ಮಾಪನಾಂಕ ನಿರ್ಣಯ ಪ್ರಮಾಣಪತ್ರವೆಂದು ಪರಿಗಣಿಸಬಾರದು.",
        "no_img_msg": "ಈ ಹಸ್ತಚಾಲಿತ ತಪಾಸಣೆಗಾಗಿ ಪ್ಯಾಕೇಜ್ ಚಿತ್ರಗಳನ್ನು ಸಲ್ಲಿಸಲಾಗಿಲ್ಲ. ಭೌತಿಕ ಓದುವಿಕೆಯನ್ನು ಮೌಲ್ಯಮಾಪನ ಮಾಡಲಾಗಿಲ್ಲ.",
        "external_verification_title": "ಬಾಹ್ಯ ನೋಂದಣಿ ಪರಿಶೀಲನೆ ಮತ್ತು ಕ್ರಾಸ್-ಪರಿಶೀಲನೆ",
        "overall_cross_check_status": "ಒಟ್ಟಾರೆ ಕ್ರಾಸ್-ಪರಿಶೀಲನೆ ಸ್ಥಿತಿ",
        "verification_confidence_tier": "ಪರಿಶೀಲನಾ ವಿಶ್ವಾಸಾರ್ಹತೆಯ ಮಟ್ಟ",
        "authoritative_verdict": "ಅಧಿಕೃತ ತೀರ್ಪು",
        "verification_sources": "ಪರಿಶೀಲನಾ ಮೂಲಗಳು",
        "cross_check_target": "ಪರಿಶೀಲನಾ ಗುರಿ",
        "extracted_value": "ಪಡೆದ ಮೌಲ್ಯ",
        "registry_record": "ನೋಂದಣಿ ದಾಖಲೆ",
        "human_review_title": "ಮಾನವ ಅಧಿಕಾರಿ ಆಡಿಟ್ ಮರುಪರಿಶೀಲನೆ",
        "review_workflow_status": "ಮರುಪರಿಶೀಲನಾ ಕಾರ್ಯಪ್ರವಾಹ ಸ್ಥಿತಿ",
        "assigned_officer": "ನಿಯೋಜಿತ ಕಾನೂನು ಮಾಪನಶಾಸ್ತ್ರ ಅಧಿಕಾರಿ",
        "verified_by_officer": "ಅಧಿಕಾರಿಯಿಂದ ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
        "verification_timestamp": "ಪರಿಶೀಲನಾ ಸಮಯ ಮುದ್ರೆ",
        "final_human_verdict": "ಅಂತಿಮ ಮಾನವ ಅನುಸರಣೆ ತೀರ್ಪು",
        "human_verified_score": "ಮಾನವ ಪರಿಶೀಲಿಸಿದ ಸ್ಕೋರ್",
        "ai_vs_human_delta": "AI ವಿರುದ್ಧ ಮಾನವ ಸ್ಕೋರ್ ವ್ಯತ್ಯಾಸ",
        "officer_notes": "ಅಧಿಕಾರಿ ಪರಿಶೀಲನಾ ಟಿಪ್ಪಣಿಗಳು",
        "detailed_compliance_checklist": "ವಿವರವಾದ ಶಾಸನಬದ್ಧ ಅನುಸರಣೆ ಪರಿಶೀಲನಾಪಟ್ಟಿ",
        "legal_metrology_title": "ಕಾನೂನು ಮಾಪನಶಾಸ್ತ್ರ (ಪ್ಯಾಕ್ ಮಾಡಿದ ಸರಕುಗಳು) ನಿಯಮಗಳು 2011",
        "fssai_title": "FSSAI (ಆಹಾರ ಸುರಕ್ಷತೆ ಮತ್ತು ಗುಣಮಟ್ಟ ಲೇಬಲಿಂಗ್ ನಿಯಮಗಳು)",
        "field_header": "ನಿಯಮ ID",
        "requirement_header": "ಶಾಸನಬದ್ಧ ಅವಶ್ಯಕತೆ",
        "status_header": "ಸ್ಥಿತಿ",
        "detected_value_header": "ಗುರುತಿಸಲಾದ ಘೋಷಣೆ",
        "finding_header": "ಕಾನೂನು ಫಲಿತಾಂಶ",
        "evidence": "ಸಾಕ್ಷ್ಯ",
        "location_header": "ಸ್ಥಳ",
        "confidence_header": "ವಿಶ್ವಾಸಾರ್ಹತೆ",
        "recommended_check": "ಶಿಫಾರಸು ಮಾಡಿದ ಪರಿಶೀಲನೆ",
        "recommended_actions_title": "ಶಿಫಾರಸು ಮಾಡಿದ ಮುಂದಿನ ಕ್ರಮಗಳು",
        "priority_header": "ಆದ್ಯತೆ",
        "rule_title_header": "ನಿಯಮ ಮತ್ತು ಶೀರ್ಷಿಕೆ",
        "issue_header": "ಗುರುತಿಸಲಾದ ಸಮಸ್ಯೆ",
        "recommended_action_header": "ಶಿಫಾರಸು ಮಾಡಿದ ಕ್ರಮ",
        "statutory_basis_header": "ಕಾನೂನುಬದ್ಧ ಆಧಾರ",
        "no_rec_msg": "ಸ್ವಯಂಚಾಲಿತ ಸ್ಕ್ರೀನಿಂಗ್ ಆಧಾರದ ಮೇಲೆ ಯಾವುದೇ ಸರಿಪಡಿಸುವ ಕ್ರಮಗಳ ಅಗತ್ಯವಿಲ್ಲ.",
        "visual_evidence_title": "ದೃಶ್ಯ ಸಾಕ್ಷ್ಯ ಅನುಬಂಧ",
        "security_integrity_title": "ಭದ್ರತೆ, ಸಮಗ್ರತೆ ಮತ್ತು ಆಡಿಟ್ ಮೂಲ",
        "integrity_hash_label": "ಕ್ರಿಪ್ಟೋಗ್ರಾಫಿಕ್ ಸಮಗ್ರತೆ ಹ್ಯಾಶ್ (SHA-256)",
        "software_version_label": "ಸಿಸ್ಟಮ್ ಸಾಫ್ಟ್‌ವೇರ್ ಆವೃತ್ತಿ",
        "ruleset_version_label": "ಶಾಸನಬದ್ಧ ರೂಲ್‌ಸೆಟ್ ಆವೃತ್ತಿ",
        "ocr_engine_label": "OCR ಮತ್ತು ವಿಷನ್ ಎಂಜಿನ್",
        "audit_status_label": "ಆಡಿಟ್ ಪರಿಶೀಲನೆ ಸ್ಥಿತಿ",
        "verification_notice_label": "ಪರಿಶೀಲನೆ ಸೂಚನೆ",
        "evidence_summary": "ಸಾಕ್ಷ್ಯ ಸರಪಳಿ ಸಾರಾಂಶ",
        "page": "ಪುಟ",
        "disclaimer": "ಮೆಟ್ರ್‌ಚೆಕ್ AI ಸಲ್ಲಿಸಿದ ಚಿತ್ರಗಳ ಆಧಾರದ ಮೇಲೆ ಸ್ಕ್ರೀನಿಂಗ್ ನೀಡುತ್ತದೆ. ಫಲಿತಾಂಶಗಳು ಅಧಿಕೃತ ಕಾನೂನು ಜಾರಿ ನಿರ್ಧಾರವಲ್ಲ.",
    },
    "ml": {
        "report_title": "AI-സഹായത്തോടെയുള്ള ഉൽപ്പന്ന അനുസരണ സ്ക്രീനിംഗ് റിപ്പോർട്ട്",
        "subtitle": "ഉപഭോക്തൃ കാര്യ വകുപ്പ്, ഇന്ത്യാ ഗവൺമെന്റ്",
        "overall_status": "നിയമപരമായ അനുസരണ സ്ക്രീനിംഗ് ഫലം",
        "compliance_score": "അനുസരണ സ്കോർ",
        "screening_score": "സ്ക്രീനിംഗ് സ്കോർ",
        "product_name": "ഉൽപ്പന്നത്തിന്റെ പേര്",
        "brand": "ബ്രാൻഡ്",
        "analysis_id": "വിശകലന ID",
        "analysis_mode": "വിശകലന മോഡ്",
        "manual_mode": "മാനുവൽ ഉൽപ്പന്ന പരിശോധന",
        "image_mode": "AI ഇമേജും OCR സ്ക്രീനിംഗും",
        "info_source": "വിവര ഉറവിടം",
        "manual_source": "ഉപഭോക്താവ് നൽകിയ പ്രഖ്യാപനങ്ങൾ",
        "image_source": "പാക്കേജ് ആർട്ട്വർക്ക് OCR-ഉം കമ്പ്യൂട്ടർ വിഷനും",
        "inspection_timestamp": "പരിശോധനാ സമയം",
        "generated_at": "റിപ്പോർട്ട് സൃഷ്ടിച്ച സമയം",
        "product_risk_tier": "ഉൽപ്പന്ന അപകടസാധ്യത നില",
        "images_analyzed": "വിശകലനം ചെയ്ത ചിത്രങ്ങൾ",
        "detected_languages": "കണ്ടെത്തിയ പാക്കേജിംഗ് ഭാഷകൾ",
        "statutory_declarations": "നിയമപരമായ പ്രഖ്യാപനങ്ങൾ (റൂൾ 6)",
        "executive_summary": "എക്സിക്യൂട്ടീവ് സംഗ്രഹവും ഉൽപ്പന്ന അവലോകനവും",
        "legal_disclaimer": "നിയമപരമായ നിരാകരണവും ചട്ടപ്പടിയുള്ള പരിധിയും",
        "items_requiring_attention": "ശ്രദ്ധിക്കേണ്ട കാര്യങ്ങളും അവയുടെ അർത്ഥവും",
        "what_this_means": "ഇതിന്റെ അർത്ഥമെന്താണ്",
        "detected": "കണ്ടെത്തി",
        "all_pass_msg": "വിശകലനം ചെയ്ത എല്ലാ പാക്കേജിംഗ് പ്രഖ്യാപനങ്ങളും സ്ക്രീനിംഗ് മാനദണ്ഡങ്ങൾ പാലിക്കുന്നു. അടിയന്തര ശ്രദ്ധ ആവശ്യമില്ല.",
        "automated_score_note": "ഈ സ്കോർ ഒരു ഓട്ടോമേറ്റഡ് സ്ക്രീനിംഗ് സ്കോറാണ്. ഇതൊരു ഔദ്യോഗിക നിയമപരമായ അനുസരണ നിർണ്ണയമല്ല.",
        "manual_score_note": "ഈ സ്ക്രീനിംഗ് ഉപഭോക്താവ് നൽകിയ വിവരങ്ങളെ അടിസ്ഥാനമാക്കിയുള്ളതാണ്. ചില വിവരങ്ങൾ സ്വതന്ത്രമായി പരിശോധിച്ചിട്ടില്ല.",
        "package_information_summary": "പാക്കേജ് വിവര സംഗ്രഹം",
        "marketed_by": "വിപണന വിവരങ്ങൾ",
        "best_before_shelf_life": "ഉപയോഗിക്കേണ്ട അവസാന തീയതി / ഷെൽഫ് ലൈഫ്",
        "batch_lot_number": "ബാച്ച് / ലോട്ട് നമ്പർ",
        "readability_title": "ഭൗതിക വായനാക്ഷമതയും അളവ് പ്രഖ്യാപന വിലയിരുത്തലും",
        "readability_score_tier": "വായനാക്ഷമതാ സ്കോറും നിലവാരവും",
        "net_qty_font_height": "കണക്കാക്കിയ ശുദ്ധമായ അളവ് ഫോണ്ട് ഉയരം",
        "min_required_font_height": "കുറഞ്ഞ ആവശ്യമായ നിയമപരമായ ഉയരം",
        "rule_12_verdict": "റൂൾ 12 സ്ക്രീനിംഗ് വിധി",
        "measurement_method": "അളക്കൽ രീതിയും ഒപ്റ്റിക്കൽ സ്കെയിലും",
        "assessment_summary": "വിലയിരുത്തൽ സംഗ്രഹം",
        "rule12_notice": "ഡിജിറ്റൽ ഇമേജ് വിശകലനത്തിൽ നിന്നാണ് അളവുകൾ നിർണ്ണയിച്ചിരിക്കുന്നത്. ഇവയെ കാലിബ്രേറ്റ് ചെയ്ത സർട്ടിഫിക്കറ്റായി കണക്കാക്കരുത്.",
        "no_img_msg": "ഈ മാനുവൽ പരിശോധനയ്ക്കായി പാക്കേജ് ചിത്രങ്ങൾ സമർപ്പിച്ചിട്ടില്ല. ഭൗതിക വായനാക്ഷമത വിലയിരുത്തിയിട്ടില്ല.",
        "external_verification_title": "ബാഹ്യ രജിസ്ട്രി പരിശോധനയും ക്രോസ്-ചെക്കിംഗും",
        "overall_cross_check_status": "മൊത്തത്തിലുള്ള ക്രോസ്-ചെക്ക് നില",
        "verification_confidence_tier": "പരിശോധനാ വിശ്വാസ്യത നില",
        "authoritative_verdict": "ഔദ്യോഗിക വിധി",
        "verification_sources": "പരിശോധനാ ഉറവിടങ്ങൾ",
        "cross_check_target": "പരിശോധനാ ലക്ഷ്യം",
        "extracted_value": "വേർതിരിച്ചെടുത്ത മൂല്യം",
        "registry_record": "രജിസ്ട്രി രേഖ",
        "human_review_title": "ഹ്യൂമൻ ഓഫീസർ ഓഡിറ്റ് അവലോകനം",
        "review_workflow_status": "അവലോകന വർക്ക്ഫ്ലോ നില",
        "assigned_officer": "നിയോഗിച്ച ലീഗൽ മെട്രോളജി ഓഫീസർ",
        "verified_by_officer": "ഉദ്യോഗസ്ഥൻ പരിശോധിച്ചത്",
        "verification_timestamp": "പരിശോധനാ സമയമുദ്ര",
        "final_human_verdict": "അന്തിമ മനുഷ്യ അനുസരണ വിധി",
        "human_verified_score": "മനുഷ്യ പരിശോധിച്ച സ്കോർ",
        "ai_vs_human_delta": "AI വേഴ്സസ് മനുഷ്യ സ്കോർ വ്യത്യാസം",
        "officer_notes": "ഉദ്യോഗസ്ഥ അവലോകന കുറിപ്പുകൾ",
        "detailed_compliance_checklist": "വിശദമായ നിയമപരമായ അനുസരണ ചെക്ക്‌ലിസ്റ്റ്",
        "legal_metrology_title": "ലീഗൽ മെട്രോളജി (പാക്കേജ് ചെയ്ത ചരക്കുകൾ) ചട്ടങ്ങൾ 2011",
        "fssai_title": "FSSAI (ഭക്ഷ്യ സുരക്ഷാ മാനദണ്ഡങ്ങൾ ലേബലിംഗ് നിയന്ത്രണങ്ങൾ)",
        "field_header": "നിയമ ID",
        "requirement_header": "നിയമപരമായ ആവശ്യം",
        "status_header": "സ്ഥിതി",
        "detected_value_header": "കണ്ടെത്തിയ പ്രഖ്യാപനം",
        "finding_header": "നിയമപരമായ കണ്ടെത്തൽ",
        "evidence": "തെളിവ്",
        "location_header": "സ്ഥലം",
        "confidence_header": "വിശ്വാസ്യത",
        "recommended_check": "ശുപാർശ ചെയ്ത പരിശോധന",
        "recommended_actions_title": "ശുപാർശ ചെയ്യുന്ന അടുത്ത ഘട്ടങ്ങൾ",
        "priority_header": "മുൻഗണന",
        "rule_title_header": "നിയമവും തലക്കെട്ടും",
        "issue_header": "കണ്ടെത്തിയ പ്രശ്നം",
        "recommended_action_header": "ശുപാർശ ചെയ്യുന്ന നടപടി",
        "statutory_basis_header": "നിയമപരമായ അടിസ്ഥാനം",
        "no_rec_msg": "ഓട്ടോമേറ്റഡ് സ്ക്രീനിംഗിന്റെ അടിസ്ഥാനത്തിൽ തിരുത്തൽ നടപടികൾ ആവശ്യമില്ല.",
        "visual_evidence_title": "ദൃശ്യ തെളിവ് അനുബന്ധം",
        "security_integrity_title": "സുരക്ഷ, സമഗ്രത, ഓഡിറ്റ് ഉത്ഭവം",
        "integrity_hash_label": "ക്രിപ്റ്റോഗ്രാഫിക് ഇന്റഗ്രിറ്റി ഹാഷ് (SHA-256)",
        "software_version_label": "സിസ്റ്റം സോഫ്റ്റ്‌വെയർ പതിപ്പ്",
        "ruleset_version_label": "നിയമപരമായ റൂൾസെറ്റ് പതിപ്പ്",
        "ocr_engine_label": "OCR-ഉം വിഷൻ എഞ്ചിനും",
        "audit_status_label": "ഓഡിറ്റ് പരിശോധനാ നില",
        "verification_notice_label": "പരിശോധന അറിയിപ്പ്",
        "evidence_summary": "തെളിവ് ശൃംഖല സംഗ്രഹം",
        "page": "പേജ്",
        "disclaimer": "മെറ്റർചെക്ക് AI വിശകലനത്തിനായി സമർപ്പിച്ച ചിത്രങ്ങളുടെ അടിസ്ഥാനത്തിൽ സ്ക്രീനിംഗ് നൽകുന്നു. ഫലങ്ങൾ ഔദ്യോഗിക നിയമപരമായ നിർണ്ണയമല്ല.",
    },
}


def localize_rule_label(rule_id: str, lang: str = "en") -> str:
    """Retrieve localized label for a rule ID (falls back to English)."""
    l = (lang or "en").lower().strip()
    labels = LOCALIZED_FIELD_LABELS.get(l, LOCALIZED_FIELD_LABELS["en"])
    return labels.get(rule_id, LOCALIZED_FIELD_LABELS["en"].get(rule_id, rule_id))


def localize_status(status: str, lang: str = "en") -> str:
    """Retrieve localized status string."""
    l = (lang or "en").lower().strip()
    s = (status or "PASS").upper().replace("-", "_")
    statuses = LOCALIZED_STATUSES.get(l, LOCALIZED_STATUSES["en"])
    return statuses.get(s, s)


def localize_explanation(
    rule_id: str,
    status: str,
    detected_value: Optional[str] = None,
    lang: str = "en",
    dynamic_explanation: Optional[str] = None
) -> str:
    """Retrieve localized explanation for a rule finding."""
    l = (lang or "en").lower().strip()
    status_upper = (status or "PASS").upper()
    
    if dynamic_explanation and l == "en":
        return dynamic_explanation

    if status_upper in ("NOT_APPLICABLE", "EXEMPT"):
        if dynamic_explanation:
            d_lower = dynamic_explanation.lower()
            if "domestically" in d_lower or "domestic" in d_lower:
                domestic_map = {
                    "hi": "घरेलू रूप से निर्मित उत्पाद — आयातित उद्भव घोषणा लागू नहीं होती।",
                    "mr": "स्थानिक पातळीवर उत्पादित उत्पादन — आयातित मूळ देश घोषणा लागू नाही.",
                    "bn": "দেশীয়ভাবে উৎপাদিত পণ্য — আমদানিকৃত উৎসের ঘোষণা প্রযোজ্য নয়।",
                    "gu": "સ્થાનિક રીતે ઉત્પાદિત ઉત્પાદન — આયાતિત મૂળ ઘોષણા લાગુ પડતી નથી.",
                    "pa": "ਘਰੇਲੂ ਤੌਰ 'ਤੇ ਨਿਰਮਿਤ ਉਤਪਾਦ — ਆਯਾਤ ਮੂਲ ਘੋਸ਼ਣਾ ਲਾਗੂ ਨਹੀਂ ਹੁੰਦੀ।",
                    "ta": "உள்நாட்டில் தயாரிக்கப்பட்ட தயாரிப்பு — இறக்குமதி செய்யப்பட்ட அறிவிப்பு பொருந்தாது.",
                    "te": "దేశీయంగా తయారు చేయబడిన ఉత్పత్తి — దిగుమతి మూల ప్రకటన వర్తించదు.",
                    "kn": "ದೇಶೀಯವಾಗಿ ತಯಾರಿಸಲಾದ ಉತ್ಪನ್ನ — ಆಮದು ಮೂಲ ಘೋಷಣೆ ಅನ್ವಯಿಸುವುದಿಲ್ಲ.",
                    "ml": "തദ്ദേശീയമായി നിർമ്മിച്ച ഉൽപ്പന്നം — ഇറക്കുമതി ഉത്ഭവ പ്രഖ്യാപനം ബാധകമല്ല.",
                }
                return domestic_map.get(l, dynamic_explanation)
            elif "fssai" in d_lower or "food" in d_lower:
                food_map = {
                    "hi": "खाद्य उत्पाद — तिथि अंकन FSSAI विनियमों के तहत मूल्यांकित होता है।",
                    "mr": "अन्न उत्पादन — दिनांक नोंद FSSAI नियमांनुसार तपासली जाते.",
                    "bn": "খাদ্য পণ্য — তারিখ চিহ্নিতকরণ FSSAI বিধিমালার অধীনে মূল্যায়ন করা হয়।",
                    "gu": "ખાદ્ય ઉત્પાદન — તારીખ માર્કિંગ FSSAI નિયમો હેઠળ મૂલ્યાંકન થાય છે.",
                    "pa": "ਭੋਜਨ ਉਤਪਾਦ — ਮਿਤੀ ਨਿਸ਼ਾਨਦੇਹੀ FSSAI ਨਿਯਮਾਂ ਅਧੀਨ ਮੁਲਾਂਕਣ ਕੀਤੀ ਜਾਂਦੀ ਹੈ।",
                    "ta": "உணவு தயாரிப்பு — FSSAI விதிகளின் கீழ் தேதி குறிப்பு மதிப்பிடப்படுகிறது.",
                    "te": "ఆహార ఉత్పత్తి — FSSAI నిబంధనల ప్రకారం తేదీ మార్కింగ్ మూల్యాంకనం చేయబడుతుంది.",
                    "kn": "ಆಹಾರ ಉತ್ಪನ್ನ — ದಿನಾಂಕ ಗುರುತು FSSAI ನಿಯಮಗಳ ಅಡಿಯಲ್ಲಿ ಮೌಲ್ಯಮಾಪನ ಮಾಡಲಾಗುತ್ತದೆ.",
                    "ml": "ഭക്ഷണ ഉൽപ്പന്നം — FSSAI ചട്ടങ്ങൾക്ക് കീഴിൽ തീയതി അടയാളപ്പെടുത്തൽ വിലയിരുത്തുന്നു.",
                }
                return food_map.get(l, dynamic_explanation)
            return dynamic_explanation
        
        na_map = {
            "en": "This requirement is not applicable for this product category.",
            "hi": "यह आवश्यकता इस उत्पाद श्रेणी के लिए लागू नहीं है।",
            "mr": "ही आवश्यकता या उत्पादन प्रवर्गासाठी लागू नाही.",
            "bn": "এই প্রয়োজনীয়তা এই পণ্য বিভাগের জন্য প্রযোজ্য নয়।",
            "gu": "આ જરૂરિયાત આ ઉત્પાદન શ્રેણી માટે લાગુ પડતી નથી.",
            "pa": "ਇਹ ਲੋੜ ਇਸ ਉਤਪਾਦ ਸ਼੍ਰੇਣੀ ਲਈ ਲਾਗੂ ਨਹੀਂ ਹੈ।",
            "ta": "இந்த தயாரிப்பு வகைக்கு இந்த தேவை பொருந்தாது.",
            "te": "ఈ ఉత్పత్తి వర్గానికి ఈ అవసరం వర్తించదు.",
            "kn": "ಈ ಉತ್ಪನ್ನ ವರ್ಗಕ್ಕೆ ಈ ಅವಶ್ಯಕತೆ ಅನ್ವಯಿಸುವುದಿಲ್ಲ.",
            "ml": "ഈ ഉൽപ്പന്ന വിഭാഗത്തിന് ഈ ആവശ്യം ബാധകമല്ല.",
        }
        return na_map.get(l, na_map["en"])

    st_group = "PASS" if status_upper in ("PASS", "COMPLIANT") else "FAIL"
    lang_templates = LOCALIZED_EXPLANATION_TEMPLATES.get(l, LOCALIZED_EXPLANATION_TEMPLATES["en"])
    tpl_group = lang_templates.get(st_group, LOCALIZED_EXPLANATION_TEMPLATES["en"][st_group])
    base_expl = tpl_group.get(rule_id, LOCALIZED_EXPLANATION_TEMPLATES["en"][st_group].get(rule_id, "Status evaluated."))

    if detected_value and st_group == "PASS":
        if l == "hi":
            return f"{base_expl} (मान: {detected_value})"
        return f"{base_expl} (Declared: {detected_value})"
    return base_expl

def get_report_ui_labels(lang: str = "en") -> Dict[str, str]:
    """Retrieve localized UI headers and labels for PDF report generation."""
    l = (lang or "en").lower().strip()
    return REPORT_UI_LABELS.get(l, REPORT_UI_LABELS["en"])
